### ISSUE TITLE
Meaning of "valid" Tosca Archive

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#10]
We have to formally define what it takes for a Tosca Archive to be considered as "Valid".

**Comment by gioppoluca** [comment]
We need it to be parsable so if we can have some basic xpath test we will be able to see it is good.
In general we could test the generation of files to check that the content produces something

**Comment by guidospadotto-profesia** [comment]
Ok, so it is just a matter of xml files being "well-formed". No checks on the "meaning" (the normative schema leaves room for extension).

**Comment by gioppoluca** [comment]
yes just be sure that using it it does not break everything
