### ISSUE TITLE
Conflict between activiti-rest and our user management

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#102]
We need to use activiti-rest, but when I include it in maven I get exceptions in the user management part (securoty boot).
Try to include it and try to fix error.

**Comment by guidospadotto-profesia** [comment]
Where exactly do you need activiti-rest and to do what. We need this information to validate the fix.

**Comment by guidospadotto-profesia** [comment]
Fixed in c3b60ea
