### ISSUE TITLE
Caching enable

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#103]
We need to use spring cache, there is a cache configuratoin but I do not understand if is disabled or not.
We need to have it configured so we can use @cachable annotation

**Comment by guidospadotto-profesia** [comment]
According to https://spring.io/guides/gs/caching/ it should be just a matter of:
1: Add the @EnableCaching annotation to eu.cloudopting.Application
2: Add the @Cacheable("<name_of_cache>") annotation on the Interface method that retrieves the entities to be cached

As I am not a Spring expert, I woulf like to ask @cpopsa and/or @pdaniel if they have any further comment/remark on this.

**Comment by gioppoluca** [comment]
Do not know if the feature is already in the bunch of dependencies we have, can you check it with Daniel?

**Comment by guidospadotto-profesia** [comment]
I will. As soon as the servers are back, I will test adding the annotation to the Application class and using @Cacheable somewhere.

**Comment by cpopsa** [comment]
At the moment Spring cache is disabled. As soon as the test db is up, I will configure the cache to use a simple implementation based on Java's ConcurrentHashMap.
If your use cases needs a more capable cache implementation (EhCache, Guava, Hazelcast etc.) please let me know.

**Comment by xeviscc** [comment]
Development database is up and running.

**Comment by guidospadotto-profesia** [comment]
I assigned this to @cpopsa because he's now responsible for the setting of the cache.

**Comment by cpopsa** [comment]
Done. To use Spring cache, you just have to add @Cacheable("default") to the method.
