### ISSUE TITLE
Endpoint /api/application GET does not return what expected.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#105]
It happens the same than in the issue #96 .

Could you please check it out?

**Comment by xeviscc** [comment]
@guidospadotto-profesia started to work on it.

**Comment by guidospadotto-profesia** [comment]
Catalin volunteered to fix this issue.

**Comment by cpopsa** [comment]
Fixed

**Comment by xeviscc** [comment]
I cannot make it work:

![image](https://cloud.githubusercontent.com/assets/10829055/11980045/1ce9e3ce-a998-11e5-919a-42fda8ad1ff7.png)

**Comment by cpopsa** [comment]
I thought you want the modification for endpoint /api/application GET. 
I made the changes for /api/application/{id} GET also.
