### ISSUE TITLE
The generated folders from the IDE conains wrong data

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#106]
Steps done:

1. Created a service.
2. Created an instance of the service.
3. Tested the application (saved in the computer's file manager)

![image](https://cloud.githubusercontent.com/assets/10829055/11974164/e5f53b92-a961-11e5-8f83-5b8530ecd2d3.png)

![image](https://cloud.githubusercontent.com/assets/10829055/11974174/f36f79b8-a961-11e5-941f-b9848d74e025.png)

In any of the both I have mentioned Mongo. I was trying to test it separately.

**Comment by gioppoluca** [comment]
I need to see the json and the tosca zip are in the pilot git?

**Comment by xeviscc** [comment]
Yes!
You can find the json files and the toscaide ZIPs generated in: https://github.com/CloudOpting/pilots/tree/master/EXP-03-CityAngenda_Next2Me/_toscaide_files
You can find the generated files for the orchestrator in: https://github.com/CloudOpting/pilots/tree/master/EXP-03-CityAngenda_Next2Me/_generated

**Comment by xeviscc** [comment]
Closed due its inactivity
