### ISSUE TITLE
Getting a JNDI Datasource for Activiti BPM Engine

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#11]
The Activity BPM Engine requires a Database to operate. The DB can be accessed by means of JNDI Datasources (see http://activiti.org/userguide/index.html#jndiDatasourceConfig ). 
How do I inject/reference the datasource that should be provided by the Database Component?

**Comment by gioppoluca** [comment]
There is a config class I wes starting to create to customize activit, but had not yet time to test it.
You can see in the package "config"
