### ISSUE TITLE
Check dependencies versions - update them and uniform them

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#114]
We have many dependencies in the project and some have different version in different component.
This has to be fixed (using the same version everywhere).
While at it check the basic and common if are the latest and check if updating to the latest breaks up something.
For all the non breaking ones, do the update.
for the most delicate ones (Activiti, jackrabbit etc) have the most care and attention :D

**Comment by guidospadotto-profesia** [comment]
I have committed an update ( eaac758 ) that checks that dependency versions are consistent, but I cannot test it as the remote DBs are still down.

Moreover, there are several SNAPSHOT dependencies (jackrabbit and jclouds) which I don't know if they are required (or if they could have a "fixed" version):

Guidos-MacBook-Pro:cloudopting-manager guido$ mvn dependency:tree -Dincludes=org.'*'| grep SNAPSHOT:
[INFO] +- eu.cloudopting:database-component:jar:1.0-SNAPSHOT:compile
[INFO] +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:common-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:database-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- org.apache.jclouds:jclouds-core:jar:2.0.0-SNAPSHOT:compile
[INFO] +- org.apache.jclouds.labs:azurecompute:jar:2.0.0-SNAPSHOT:compile
[INFO] |  \- org.apache.jclouds:jclouds-compute:jar:2.0.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:common-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:database-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:common-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:database-component:jar:1.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:storage-component:jar:1.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:cloud-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jclouds:jclouds-core:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jclouds.labs:azurecompute:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.apache.jclouds:jclouds-compute:jar:2.0.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:common-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:database-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:tosca-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:storage-component:jar:1.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:bpmn-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:cloud-component:jar:1.0-SNAPSHOT:compile
[INFO] |  |  +- org.apache.jclouds:jclouds-core:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.apache.jclouds.labs:azurecompute:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |     \- org.apache.jclouds:jclouds-compute:jar:2.0.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:common-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.jackrabbit:jackrabbit-api:jar:3.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:monitoring-component:jar:1.0-SNAPSHOT:compile
[INFO] +- eu.cloudopting:tosca-component:jar:1.0-SNAPSHOT:compile
[INFO] |  +- eu.cloudopting:storage-component:jar:1.0-SNAPSHOT:compile

**Comment by gioppoluca** [comment]
For those we need to check if there are the RELEASE version now or are still in that state (for sure we need at least the SNAPSHOT, but it could be released since august)
For both we need a word from Daniel

**Comment by guidospadotto-profesia** [comment]
Closing this and opening a new "Remove SNAPSHOT dependencies" issue, I'll assign it to @cpopsa (to study JackRabbit) and he will then assign it to whoever added JClouds.
