### ISSUE TITLE
Create users in the DB

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#116]
We need to have a user for each partner in the DB.
As soon as the env is up please create an account for each partner (username=partner ; password make it all the same but not trivial).
This is needed to start generating the pilot with the right name and all the right things working we need to check processes with the proper users and not always as admin.
Also we need a similar account for subscriber so username=partner-sub

**Comment by gioppoluca** [comment]
Also this should be easy to do, please try to close it today

**Comment by guidospadotto-profesia** [comment]
@xeviscc Do we have the UI to perform this task as admin user?

**Comment by xeviscc** [comment]
Yes, you can find it in the "Development Menu".

![image](https://cloud.githubusercontent.com/assets/10829055/12509356/293cef82-c102-11e5-9e01-81de684a7ee9.png)

**Comment by guidospadotto-profesia** [comment]
Done in **dev** DB.
Subscriber user has the "sub" suffix.

**Each partner has to edit its accounts to set an existent e-mail address and adjust their roles.** 

<img width="1108" alt="issue_116" src="https://cloud.githubusercontent.com/assets/12183654/12643531/efb7a292-c5bc-11e5-8ceb-4c1ed852725b.png"
