### ISSUE TITLE
complete the test procedure

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#117]
At the moment the test button generate the folder with all the files for docker and puppet.
These files are placed in the file system.
We need to generate a zip on the fly return it as a conseguence of the pressing of the button test and than deleting the folder.

We need to talk together on how to do it will be faster on a call

**Comment by gioppoluca** [comment]
I added the backend part now the test call return the file, but is placed in the data variavle as stream and does not get opened the saveas window.
We need a angularjs module that does that trick can you add it?:
https://github.com/alferov/angular-file-saver

**Comment by xeviscc** [comment]
The zip archive will be created after clicking the button or will be there waiting for someone to download it?

**Comment by xeviscc** [comment]
A new update has been pushed. Check it.
