### ISSUE TITLE
Find an editor for the description of the service

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#119]
We need to be able to have a rich description of the service so we need to have a rich text editor there.
HTML generated needs to comply with site CSS style.

Need to find one and propose it to WP2 team than apply

**Comment by gioppoluca** [comment]
We should use textAngular:
http://textangular.com/.
Can you try to apply it to the exsisting description field?
Thanks
Luca

**Comment by gioppoluca** [comment]
Can we have a sprint on this, possibly closing it today, should be quick

**Comment by xeviscc** [comment]
It was evaluated together with our Design team and they advise us that this sort of editors may broke all the "look & feel" of the site.

Are we ready to manage it?

**Comment by gioppoluca** [comment]
we need to have it to have a proper professional description, the other option is to have dedicated fields for all the pieces of info and it could be more a mess on the coding, I see lots of text editors that do not break L&F and the proposed one should not, let us try to see the design, while we apply the text editor and we'll see, but today apps have this sort of features

**Comment by xeviscc** [comment]
Added textangular to the description of the service.
