### ISSUE TITLE
Screens definition.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#12]
The screens needed for the Wordpress component has to be defined.

In the deliverable 2.2, section 5.1 Graphical User Interface, it is not clear the difference between the Wordpress and the WebUI.

**Comment by guidospadotto-profesia** [comment]
The WebUI is a sort of Management Console for the Back-end (from a technical point of view).
On the other hand, the Catalogue Portal is a sort of "Apple Store" that will be used to Publish and Commercialize the services installed in the CloudOpting Platform.

**Comment by gioppoluca** [comment]
The screens shown in the review by Riera were not for the catalogue? I understood that some )the nice ones) were for the catalogue, the others the recorded demo from the webUI.
In any case we need a very similar interface so we need to have a wordpress template done with standard UI and use the same for the webUI (same CSS and possibly page structure)
