### ISSUE TITLE
Apply new UI design

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#121]
As discussed today, we need it asap from design team than pass it to Guido

**Comment by xeviscc** [comment]
We sent an email to the design people in order to have more resources to integrate it as sooon as we can.

**Comment by gioppoluca** [comment]
We need an update on this

**Comment by xeviscc** [comment]
The screens planned have been migrated. 
Other screens not planned have also been migrated.
If you find some important screen not migrated, please open a new issue or reopen this one.
