### ISSUE TITLE
Dashboard for the subscriber

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#124]
A new screen with a Dashboard for the subscriber has to be done.

The screen will contain:
* A list of all the services he bought.
* Each service on the list will have a button asociated in order to check the "Monitoring"
* On "Monitoring" button click a statisctics and monitoring screen will be shown about this particular instance.

**Comment by gioppoluca** [comment]
Correct I would also ask WP5 on the optoing to opt out of the service, like a comunication button or a "open issue" button and so on.
Maybe at the moment we do not do anything but we can shoe that we plan to do it; also on the video it will be more professional

**Comment by xeviscc** [comment]
The dashboard has been created.
