### ISSUE TITLE
How to insert kibana dashboard into the orchestrator

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#126]
We have to try to integrate the kibana dashboards into our angularjs platform.

In May of 2015 it was not possible: https://github.com/elastic/kibana/issues/3752

**Comment by gioppoluca** [comment]
I believe that we are going for a different approach:
We will issue a requrest to elasticssearch from spring, getting the result and generating the chart
This also bacause we need to sedn in the proper query (my service, and my logs and a particular reg exp of the path.
in this way we can have a list of reg exp for each service that will become a list of query for each customization and become a list of charts in the dashboard of the service.
getting the data in spring is already done, I need to generate the json and send to meteorjs as we already did last august

**Comment by gioppoluca** [comment]
I need to understand how to query elasticsearch if we have any elasticsearch expert we need him now

**Comment by gioppoluca** [comment]
Done the elastic search part now will need to map the elastic with the javascript lib for graph than is done.
We will not integrate kibana but plot our own graphs

**Comment by guidospadotto-profesia** [comment]
Reassigning this issue to @gioppoluca . Feel free to reassign it back to me when all is ready.

**Comment by gioppoluca** [comment]
We have the things integrated with elastic so we are done with kibana
