### ISSUE TITLE
ACL definition for screens

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#127]
Each screen has to be properly cataloged. Not all the screens have to be seen by all roles, so it has to be defined and stated.

**Comment by xeviscc** [comment]
We need the flow of each role in order to decide which are the apropiate role to see a specific screen.
It has to be defined for @CloudOpting/sdggroup

**Comment by genismauri** [comment]
We will imagine/propose the screens for each role.

**Comment by MiquelBonetSDG** [comment]
Please find in the following [link](https://docs.google.com/document/d/1DnQFORr80TmvVkm8LhBw8U1Zm9KerKZDXDbo0ErdDWs/edit?usp=sharing) a first proposal for the screens of the UI to be seen by the different roles of CloudOpting (SS, SP & PP).

All comments are welcome.

**Comment by MiquelBonetSDG** [comment]
[WP5_Web screens of CloudOpting.docx](https://github.com/CloudOpting/cloudopting-manager/files/117518/WP5_Web.screens.of.CloudOpting.docx)

**Comment by xeviscc** [comment]
Seems that this already is in place. Closing it.
