### ISSUE TITLE
create a page for trying to merge toscaIDE in the orchestrator

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#128]
Let us try to see if we manage to have a page visible only to service provider to try to place the toscaIDE inside the orchestrator.
I need a page much like the "button" page at the moment so I can try to take it and port it there.
If you can also remember me where I have to place javascript that has to be applyed just to that page.
Thanks

**Comment by xeviscc** [comment]
We have to define where to put the link to access it.

**Comment by gioppoluca** [comment]
at the moment choose a link in the SP dashboard, it is something that just SP and admin can see, we need the SP landing page so there is the place I leave to you the decision, I just need an empty page and you can see in the IDE code the javascript libraries needed (mind the versions, but once you manage to place it we will check that together or I will)

**Comment by xeviscc** [comment]
A link may change, so I do not know if it is a good idea

**Comment by gioppoluca** [comment]
place in the SP dashboard a button or link that goes to "generate tosca file" that will be the IDE page

**Comment by gioppoluca** [comment]
Can you create an empty page in the UI (like the "press the button").
With the following JS libraries?
tv4.js
cytoscape.js (2.4.9 not higher)
ObjectPath.js

and an empty JS file where I can place the directive I have created?

**Comment by gioppoluca** [comment]
Call it "ide"

**Comment by xeviscc** [comment]
You can see the button if you signed up as a "Publisher".

The files to modify are in the folder:
**cloudopting-manager\rest-component\src\main\webapp\scripts\app\service\toscaide**

**TOUCHABLE:**

- toscaide.controller.js
- toscaide.directive.js
- toscaide.html

**NOT TOUCHABLE:**

- toscaide.js

**Comment by xeviscc** [comment]
@gioppoluca I saw a commit with a comment that the IDE is working. Could this issue be closed?
