### ISSUE TITLE
REST API Auth

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#13]
A method to validate the user has to be defined.

At the moment in the required rest api for the WebUI an dynamic apikey is defined.

**Comment by gioppoluca** [comment]
We need to have a complete logging/registration system
Please find something existing not invent anything from scratch.
Also we need to finalize the technology in the WebUI to find something that with work well with it

**Comment by xeviscc** [comment]
The WebUI has been integrated to the cloudopting-manager project. This endpoint is not needed anymore.
