### ISSUE TITLE
prepare template for description

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#130]
A template for the description is needed

**Comment by gioppoluca** [comment]
I'm trying to understand where I have to change things to present a default value in the description in the publish process, but have difficulty in understanding where I need to place it.
Can you please chek it and add the default string "GIOPPO_TEMPLATE" so that I can than easily find it and substitute it with the proper HTML template?
Do not know if needs to change JS or javsa
Thanks

**Comment by xeviscc** [comment]
I do not understand what do you need.
In the description of the service there are a rich text editor, and you are able to put in there whatever you need/want.
Or do you mean that you want a prefixed template inside the description of the service?
ej:
```xml
<description>[PUT HERE THE DESCRIPTION]</description>
<pricing>
  <plan>
    <amount>$10</amount>
    <description_plan>[DESCRIPTION_PLAN]</description_plan>
  <plan>
  <!-- More plans can be added -->
</pricing>
```

**Comment by xeviscc** [comment]
At first it can be placed a default template in:

- publish_one.html file
- line 68
- inside <text-angular> tag

**Comment by gioppoluca** [comment]
Fixed but now the data is correctly stored in the DB but wrongly displayed in the catalogue since all is placed inside a <p> tag and represented as textual html and not code (look ad "aClearo" example

**Comment by xeviscc** [comment]
Could you please upload a snapshot. I do not have the environment ready.

**Comment by xeviscc** [comment]
I see that when you want to display something you have to use a special tag.

See https://github.com/fraywing/textAngular/wiki/Displaying-HTML

**Comment by xeviscc** [comment]
We should think about having to descriptions. One short for the catalog and the long one for the detail.

**Comment by gioppoluca** [comment]
Agree we need that.
I add the request to an exsisting issue

**Comment by xeviscc** [comment]
Depends on #167

**Comment by xeviscc** [comment]
The template is already working, we will add new descriptions once they are done.
