### ISSUE TITLE
Problem with adding spring-boot-starter-data-elasticsearch

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#131]
I have the same problem in adding spring-boot-starter-data-elasticsearch.
Jumps up a lot of errors in the userRepository and security like was for activiti.
Maybe is a simple fix like the one you already did.
interested pom is the one in monitoring-component

**Comment by gioppoluca** [comment]
Give this priority after closing issues on M1.0.1

**Comment by guidospadotto-profesia** [comment]
Please describe the steps to reproduce. Add it where and how?

**Comment by guidospadotto-profesia** [comment]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
        </dependency>

in monitoring-component

**Comment by guidospadotto-profesia** [comment]
Seems fixed with the latest commit
