### ISSUE TITLE
Integrate the TOSCA IDE in the cloudOpting Platform 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#133]
Integrate the TOSCA IDE in the CloudOpting Platform.

We have to define where to put the link to access it.

**Comment by xeviscc** [comment]
@gioppoluca It is a duplicated issue of https://github.com/CloudOpting/cloudopting-manager/issues/128 ?

**Comment by gioppoluca** [comment]
Yes it is :D
