### ISSUE TITLE
CRUD Operations on publishing-related "entities".

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#134]
CRUD Operations on publishing-related "entities".

**Comment by guidospadotto-profesia** [comment]
Please refine this requirement, which entities?

**Comment by guidospadotto-profesia** [comment]
Closing this issue due to lack of details. Whoever asked for it in the first place will take care of writing a new issue with the relevant details and explanations.

**Comment by xeviscc** [comment]
We close it, but we will reopen it, once we talk with business and properly define the workflow and business needs for publishing
