### ISSUE TITLE
Let it be possible to add additional files during service publication/creation.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#135]
Analyze: Let it be possible to add additional files during publication/creation.

**Comment by guidospadotto-profesia** [comment]
Please bear in mind that multiple asynchronous requests for upload might cause issues with Activiti's engine (concurrent modifications of service variables across transactions).

**Comment by guidospadotto-profesia** [comment]
I need the path that I have to follow in the Platform Webapp to reach the "customisation".

**Comment by xeviscc** [comment]
It will only work on *nix based OS.

Service List -> List Instances (from one of the services) -> New Instance

**Comment by xeviscc** [comment]
Sorry, the issue is not refering to customization but creation of a service. Changing the title

**Comment by gioppoluca** [comment]
Please le ave this issue alone there is much to re design to implement this since the first requirement is that the dynamic form is able send files 



Inviato da Libero Mail per iOS


mercoledì 10 febbraio 2016, 12:15 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by guidospadotto-profesia** [comment]
@gioppoluca I think this issue is about publishing, not customising.

**Comment by xeviscc** [comment]
Should we put it in the backlog?

**Comment by ildave** [comment]
@xeviscc, can you be more clear: in which part of the publication process 
 should be possible to add more file?
In the "upload needed files" is already possible to add more than one file, but there are some issue (#355)

Can you explain me better? Thanks

**Comment by xeviscc** [comment]
If the activiti process allows to upload more than one file in the "upload needed files" screen it should be closed.
