### ISSUE TITLE
Manage the "Status" evolution of a service.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#136]
Manage the "Status" evolution of a service.
* We need to agree on what state changes imply

**Comment by gioppoluca** [comment]
We need to have some feedback form WP5 on this, we can figure out some but better to check with business.
Proposed are:
- in draft (you add with the publish process, but do not press the publish button, service visible to the SP but not in the catalog)
- in test (the publishing process is finished, but not publicated so used internally for doing tests so SP can do deployment and test, but to its own use)
- published (service published in the catalogue and subscribers can get it)
- deprecated (service is in the catalogue just for history, but subscribers cannot subscribe to it)
- retired (service is no more showned in the catalogue, but could have still some running instances, this depends on the business)
All status changes should have also some comments possibly

**Comment by gioppoluca** [comment]
Genis can you place the content of the doc somewhere in the web I did not receive it

**Comment by genismauri** [comment]
Sure Luca! I guess it can be shared are.
[WP5_Life cycles of CoudOpting.docx](https://github.com/CloudOpting/cloudopting-manager/files/103661/WP5_Life.cycles.of.CoudOpting.docx)

**Comment by genismauri** [comment]
@xeviscc @gioppoluca I believe the lifecycle is clear right now.
Can this be closed? Or any other help is needed?

**Comment by genismauri** [comment]
@xeviscc is this already covered?

**Comment by xeviscc** [comment]
We will be checking it once people uses the platform. Left it open just in case.

**Comment by genismauri** [comment]
@xeviscc I suggest to close this if implemented.
In the event we notice a malfunctioning, we can open another with the specific bug to be fixed.

**Comment by xeviscc** [comment]
I agree, new issues should be open if an error is detected.
