### ISSUE TITLE
add columns to applications table

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#137]
To better manage the mail sending we need:
+ application_subscriber_mail column type text
+ application_sp_mail type text
this is linked to #129 

Than add the column:
+ application_is_tryable type boolean

Also change the entity accordingly and the publishing first page also

**Comment by gioppoluca** [comment]
linked to #167 all these columns better go together

**Comment by cpopsa** [comment]
Done
