### ISSUE TITLE
subscriber canno manage cloud account

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#140]
There is no way for the subscriber to manage the cloud accounts.
We need in the Account menu a "manage cloud account" link to the cloud account management pages:
list of the cloud account of "that" organization and the possibility of adding more etc.

**Comment by gioppoluca** [comment]
Check also SP role and admin, all need to be able to manage cloud accounts:
SP as the subscriber
the admin need to see the list but cannot see the password or data inside the records so only list the records and be able to delete them but no edit

**Comment by xeviscc** [comment]
The "Account" in the menu will be deleted. To access the cloudaccount management you have to click in "Name: <name>"  in order to access to the profile. Then you will find a CloudAccount tab to manage cloud accounts.
