### ISSUE TITLE
subscriber password does not work

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#142]
login as subscriber: account -> password -> nothing

expected behaviour: change password page

**Comment by xeviscc** [comment]
The upper menu will be deleted in the future. if you want to change the password:

Click on the Name: <name> --> password --> Enter new password --> Save button

![image](https://cloud.githubusercontent.com/assets/10829055/12546539/d3925630-c34a-11e5-9147-9e44bffada5b.png)
