### ISSUE TITLE
Return at the end of customization form

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#144]
What is the return of the API "/application/{idApp}/sendCustomizationForm" that you expect?

**Comment by xeviscc** [comment]
At the moment it does not check the returned data.

For the specification of the endpoint we can add a management of the "HTTP Status Code" as follows:

|201	|Created|
|401	|Unauthorized|
|403	|Forbidden|
|404	|Not Found|

**Comment by gioppoluca** [comment]
any error message in case of faliure,
how do you do with other API calls?
Can you pinpoint me to a working example?

**Comment by gioppoluca** [comment]
You should have the proper http codes check it so we can go on
