### ISSUE TITLE
jackrabbit does not store tosca data properly

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#145]
Look at the jackrabbit browser.
It seems that the way we store and read are different.
It store in a single folder using '/' but than we try to traverse the folders.
Obviously in the end it fails

**Comment by guidospadotto-profesia** [comment]
The store path in Jackrabbit is created like this (see line 76 of PublishToscaUploadTask.java):
remoteFilePath 	= StoreService.getTemplatePath(org.getOrganizationKey(),uploadToscaName)
and it is not "flat". 
What is the URL to the JCR repository? (With the latest changes in the dev servers... I got lost)

**Comment by xeviscc** [comment]
You can find all URL here: https://github.com/CloudOpting/cloudopting-manager/tree/7ff7b3cfe0da39bdac7ca4c64be0b5cd80165839/rest-component/src/main/resources/config

**Comment by guidospadotto-profesia** [comment]
http://lab1.cloudopting.org:8083/server/default/ seems pretty "empty".

**Comment by gioppoluca** [comment]
http://lab1.cloudopting.org:8083/ is the place to go than browse and you find the wrong folder

**Comment by guidospadotto-profesia** [comment]
Thank you Luca. Please try publishing a service with the latest code (after commit a5413c6 )

**Comment by gioppoluca** [comment]
Fixed
