### ISSUE TITLE
User with publisher role cannot see the list of services nor the publishing menu

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#148]
I've created a user with the publisher role and cannot do published operations, no menu available

**Comment by xeviscc** [comment]
I just went to LAB1 (http://lab1.cloudopting.org:8080/cloudopting/#/publish) and I can access throught the Development Menu to the publish service.

![image](https://cloud.githubusercontent.com/assets/10829055/12576600/2e7621f6-c415-11e5-98ca-5e75b4b48c2f.png)

**I will add permissions to see its owned services**

**Comment by gioppoluca** [comment]
I created a user with JUST the publisher role not the admin like the exsisting publisher user and cannot see the list page not tryed the publish but the menu does not show the list option.

**Comment by xeviscc** [comment]
It has been created with the default "ROLE_SUBSCRIBER" and "ROLE_USER" roles. Will check it out.

**Comment by xeviscc** [comment]
It might be related to issue https://github.com/CloudOpting/cloudopting-manager/issues/143

**Comment by gioppoluca** [comment]
I see in the DB the user is a subscriber but I choose publisher, could be related to #143
