### ISSUE TITLE
Charting - redesign

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#150]
It seems that we need a simpler charting tool.
We need:
1) to be able to generate dynamically a number of charts (that is we need to have an api that tell angular the number and type of chart with the needed info to prepare the page and than to call a "getData" api for all the charts in the page
2) we need something with a directive since even this way it will be complex.
3) we need a strong lib in the timeline charting since we have that sort of need
4) we should look for something that make also easy to change the time in x axis

Looking at https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives seems promising
Let me know if you have other proposals

**Comment by xeviscc** [comment]
Analyzing if the current charts are enough.

**Comment by gioppoluca** [comment]
We also need:
5) being able to move the time range of observation
6) data returned needs to be simple

**Comment by xeviscc** [comment]
Same as https://github.com/CloudOpting/cloudopting-manager/issues/156 ?
We should close one.

**Comment by xeviscc** [comment]
For more information see #156

**Comment by xeviscc** [comment]
Check how to manage time with:
https://github.com/dangrossman/bootstrap-daterangepicker

**Comment by xeviscc** [comment]
@gioppoluca I saw that you already integrated the bootstrap-daterangepicker to the monitoring page. Any other action is required?

**Comment by gioppoluca** [comment]
yes I heve not jet finished it just added the range date but it does nothing ahahah needed #266 to go on

**Comment by xeviscc** [comment]
#266 is closed.

**Comment by xeviscc** [comment]
@gioppoluca Do you have an update on this issue?

**Comment by xeviscc** [comment]
@gioppoluca Can we close this issue?

**Comment by xeviscc** [comment]
Happy with actual charts.
