### ISSUE TITLE
Generate new table in DB x monitoring info

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#151]
We need to have a new table called monitoringInfoElastic in the DB (both dev and production)

The table needs to have the following columns:

id = sequence for the id of the monitoring info
id_customization = the foreign key to the customization table since each monitoring info relate to a specific customization
container = string that will save the container name that will be used to filter the elastic search data
condition = the string for the  condition/reg exp used to get the records in elastic search
fields = the string with the list of fields used to apply the condition
type = string; the type of monitoring done (could be linear of aggregate
description = text; the description for the chart
title = string; the title for the chart

We need to have the Java code to manage the new entity and the code also to allow to getting the list of records given the customization_id

**Comment by gioppoluca** [comment]
Add also a column of type integer named "pagination" thanks

**Comment by cpopsa** [comment]
Done in both dev and prod. Table is monitoring_info_elastic
