### ISSUE TITLE
generate API to return list of monitoring elasticsearch for the service

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#152]
The api will be:
/monitoring/elastic GET
and will return a json with the data from the table of monitoringinfoelastic

**Comment by gioppoluca** [comment]
depends on #151

**Comment by gioppoluca** [comment]
API will be /monitoring/elastic/list/{customizationid}
since we need to get the monitoring info of that customization instance

**Comment by gioppoluca** [comment]
| Description |  Values |
|---|---|
| **Description:** |  we need to read the list of monitoring info in the new table from #151 filtered by customizationid |
| **Screen that needs the endpoint:** |  monitoring page |
| **Endpoint required:** |  /api/monitoring/elastic/list/{customizationid} |
| **Call Type:** | GET|

**Comment by cpopsa** [comment]
Done. The API is /api/monitoring/elastic/info/list/{customizationId}
