### ISSUE TITLE
Service monitoring page

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#156]
The page needs to have the servica name, the customization ID and needs to show the 2 type of charts:
zabbix + elastic:
SP and Admin see zabbix and elastic
subscriber see just elastic

**Comment by xeviscc** [comment]
Depends on https://github.com/CloudOpting/cloudopting-manager/issues/154

**Comment by gioppoluca** [comment]
We will have a graph with a single series per graph.
So will have to change the graphDAO using a elasticGraph so you can plot an easy one

**Comment by xeviscc** [comment]
Now the graphs are a drawing from the instance selected.

**Comment by xeviscc** [comment]
@gioppoluca What else do we have to do in the monitoring page?

**Comment by gioppoluca** [comment]
Each graph should have to possibility to choose the time filter but I'm still trying to figure out how in a simple way looking for an example in morris.
other wise at the moment you get the last 5 events.

**Comment by gioppoluca** [comment]
Found
please add this JS lib:
https://github.com/dangrossman/bootstrap-daterangepicker
thanks

**Comment by xeviscc** [comment]
Same as https://github.com/CloudOpting/cloudopting-manager/issues/150 ?
We should close one.

**Comment by xeviscc** [comment]
For more information see #150
