### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by ignasijr** [CloudOpting/cloudopting-manager#157]
Label for password is wrong.

Organisations should exist, cannot create a new one.

![image](https://cloud.githubusercontent.com/assets/10829057/12586632/54f6152a-c451-11e5-9167-2aa7d8fc7f83.png)

**Comment by ignasijr** [comment]
perhaps a link to register an oprganisation whould be nearby..

**Comment by xeviscc** [comment]
The screen you are talking about it the creation of user in the User Manager, and now the label "Password" is fixed and a link to the "Organization Manager" has been added next to the organizations combo.

![image](https://cloud.githubusercontent.com/assets/10829055/12605445/754d0eb8-c4c5-11e5-8309-ba8bfbbad126.png)

The user registration is the following:

![image](https://cloud.githubusercontent.com/assets/10829055/12605364/a62b741c-c4c4-11e5-9f2f-d3999ad6b3f8.png)
