### ISSUE TITLE
CREATE A USER

### ISSUE THREAD

**Issue by ignasijr** [CloudOpting/cloudopting-manager#158]
I have created a user but does not list in the final list, perhaps paging is not implemented.

![image](https://cloud.githubusercontent.com/assets/10829057/12586800/01eead0a-c452-11e5-8401-e09cafecfc17.png)

**Comment by xeviscc** [comment]
The last user was created by me at: "2016-01-26 11:12:33.308"

Tried to create a new user (Z New User) and get the following list:

![image](https://cloud.githubusercontent.com/assets/10829055/12605570/6487a844-c4c6-11e5-8a17-58273e252502.png)
