### ISSUE TITLE
Filter on the service list does not work

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#160]
I log in with CSI account and see all the services list I shopuld see just the ones belonging to the CSI organization

**Comment by gioppoluca** [comment]
related to #123 this is an example of the problems we have with not checking proper permissions or not doing query properly

**Comment by xeviscc** [comment]
At the moment the endpint does not allow this type of filter. I will implement it into the UI.

**Comment by gioppoluca** [comment]
Xavi no workaround please let us ho on other tasks

**Comment by xeviscc** [comment]
Whe should be able to filter applications by the organization id.

We should modify the endpoint: GET /api/application
