### ISSUE TITLE
Cloud account after customization

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#163]
After we submit the customization we should have another page where we ask the user to choose a cloud account from the ones he can see.
Otherwise when we go to the deploy we have no clue (maybe we should have a call on this since we started it but due to bugs this task got haning for too long and there could be some misunderstandings.

**Comment by gioppoluca** [comment]
At the moment the cloud account is empty.
I should get a list that I could choose from just the one I want.
We need this fixed with rpiority since it block all the testing also for the swedish tema

**Comment by xeviscc** [comment]
The following screen is working after clicking TestApp1, Demo or Deploy it appears the following screen (Check commit e4109f9f7d4c90ff08b64b07b67a927394e4bcb6)

![image](https://cloud.githubusercontent.com/assets/10829055/12642055/b942bb74-c5b3-11e5-8100-46145f2319c9.png)

**Comment by gioppoluca** [comment]
As by phone call we need to do the choice of the cloud account after customization form.
This way in the deployment, test and demo we do not have to do anything more.

**Comment by xeviscc** [comment]
Depends on #193

**Comment by gioppoluca** [comment]
@xeviscc  Why the dependency?
After the customization form you invoke and API that does many things and ansl save the customization than returns a string, do you need another type of return?

**Comment by xeviscc** [comment]
We need to modify the endpoint POST /api/application/{idApp}/sendCustomizationForm in order to have the brand new customization to have the ID and to be able to assign the cloud account in the next screen.

**Comment by xeviscc** [comment]
I uploaded a possible solutio, could you please test it?

**Comment by gioppoluca** [comment]
it works but not save the cloud account to the customization (at least not at the actual pull)
