### ISSUE TITLE
add email to organization table

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#168]
We need to have the email column on the organization table to know to whom send the mail once someone do a subscription.

All the java stuff also

**Comment by gioppoluca** [comment]
Also add a contact_representative string column

**Comment by gioppoluca** [comment]
and a contact_phone (string)

**Comment by xeviscc** [comment]
Take into account that we have dev and prod databases

**Comment by cpopsa** [comment]
Done both in dev an prod db
