### ISSUE TITLE
add suspend feature

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#169]
This will mean:
1) add a suspend button in the UI for the subscriber user in the service monitoring page (there there will be 2 buttons 1 for suspend 1 for reactivate)
2) add a suspend button in the instance list page for each instance (this is for the SP)

this feature is available to subscriber [admin] and SP

**Comment by gioppoluca** [comment]
Let us start creating the UI

**Comment by xeviscc** [comment]
Suspend could be the same as "Stop". We already have a "Stop" button on the Instances list. If not, could you define the differences between "stop" and "suspend"

**Comment by gioppoluca** [comment]
stop will do

**Comment by xeviscc** [comment]
Indeed. We will use the existing button.
