### ISSUE TITLE
add reactivate feature

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#171]
This is the opposite of the #169 

The feature is restart the machines

**Comment by xeviscc** [comment]
Reactivate could be the same as "Start". We already have a "Start" button on the Instances list. If not, could you define the differences between "start" and "reactivate"

**Comment by gioppoluca** [comment]
Agree we can have only start

**Comment by xeviscc** [comment]
Indeed. We will use the existing button.
