### ISSUE TITLE
add legal documents to the service

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#172]
We already save the image we need to save also a known set of documents.

We need the final list and than Guido will change the publish process to allow also those files to be uploaded.

Mind that they cannot be placed in the generic files page since these are not related to the tosca stuff.

**Comment by gioppoluca** [comment]
@genismauri you have to write here the final list with names and than assign the task to @guidospadotto-profesia

**Comment by genismauri** [comment]
Luca, we go further than the service:

First, **Organisation validation**
- Legal Entity Form.
- A copy of an official document legally establishing the organisation.
- A copy of an official document proving the VAT number.

Second, **Service publication**
- Contract CloudOpting-Service Provider (last signed version uploaded, process carried out offline)
- Service File Description (to be displayed in the Catalogue)
- Terms and Conditions (to be displayed in the Catalogue)

Third, **Service subscription**
- Contract CloudOpting-Service Subscriber (last signed version uploaded, process carried out offline)

**Comment by gioppoluca** [comment]
@genismauri this is too much for a single issue [but you are not a developer.
Here we keep only the service publication stuff all the other will go in a separate issue.

**Comment by genismauri** [comment]
OK

**Comment by gioppoluca** [comment]
@guidospadotto-profesia do we create a new table or add columns?

**Comment by guidospadotto-profesia** [comment]
If the three documents (Contract, Service File Descriptor, Terms and Conditions) are mapped as 1:1 with services, I would add two columns of PostgreSql type "Text" for Service File Descriptor and Terms and Conditions and a column with a reference to a JackRabbit node that contains the Contract (like it is now for the Tosca CSAR).

**Comment by gioppoluca** [comment]
Service file description I find no use of and really do not understand if is an architacture document that deeply explain the product much like a pdf brochure should be a doc in jackrabbit, but for sure we do not publish the "service file in the WP3 terms" since is a really not useful doc for the end user.
terms are already a text field in the table so that is done.
It leaves the contract that I really do not understand if is a template of contract or not.
If is the "signed contract" has to go on the customization table and not in the application since in the application we keep generic things; but I vote against keeping CRM related things here in the catalogue.
The contract is something that will be saved by any organization in the CRM environment and not here that is an operational tool and not a CRM.
For @genismauri please keep in mind the difference between the two world, for sure the service provider or the cloudopting provider will have its own CRM and will keep all those stuff there and not here, so will the customer, no use of duplicating the info here.
want opinon also of others  ( @xeviscc , @ciprianpavel ) , this will require a talk in WP2 or WP5 call

**Comment by gioppoluca** [comment]
After some considerations the final decision is:
Any generic document related to the service will be placed somewhere on the web and linked in the description of the service using HTML link.
Terms and condition will be placed in DB as text field as per issue #173 
Contracts will not be managed in the platform since all stakeholders will own their own CRM where these documents are managed and keeping it in CO is a waste of development energy for a duplication of feature

**Comment by xeviscc** [comment]
These should be included in the description template of a service.

<strong>Following the links to the "Terms and conditions"</strong>

and more sections if needed.
