### ISSUE TITLE
add platform_price and service_price to application

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#175]
We need to have 2 more columns to application tables:
application_price
service price
both string since we could have just the price description that coudl be an amount per month etc.
The user will be able to choose it checking a box and nothing else.
All java and DBs to be chenged.

Linked to #174 since add columns to same table

**Comment by gioppoluca** [comment]
@genismauri please validate this issue and than assign to @cpopsa

**Comment by genismauri** [comment]
application_price > **YES**
service_price > **YES**

BUT this should be for the 4 segments/sizes considered in the Business Plan:

- application_price_small
- application_price_medium
- application_price_large
- application_price_extra_large
- service_price_small
- service_price_medium
- service_price_large
- service_price_extra_large

**Comment by gioppoluca** [comment]
NO!!
As already said many times there no implementation in the catalogue to managing sizing in that way.
Each service will have its own 2 prices and sizing becomes a replica of the same service with a different title, this is the maximum possible at the moment.
So:
Clearò - small city
Clearò - big City
Clearò - world

Reasons for needing different instances: the topology could/should be different (price change because more resources are used)

Also not all service could require all different sizing.
At the moment that is what we can do.
Aggregation of same services under a second entity is something that will have its own issue and go for sure on late milestones

**Comment by genismauri** [comment]
OK with the aggregation of same services under a second entity, not so fancy but no problem.

But this conflicts with the Business Plan. Already considered for the financial calculations:
Clearò - small city
Clearò - medium city
Clearò - big city
Clearò - super big city

What does "world" mean?

**Comment by genismauri** [comment]
@gioppoluca @xeviscc Just to clarify, if this was moved to 3.0.0, how this issue is solved in the current 2.0.0?

**Comment by xeviscc** [comment]
Each service can define its cost:

![image](https://cloud.githubusercontent.com/assets/10829055/13806705/78099ae0-eb5d-11e5-99e2-82eec9404c51.png)

I think you can close the issue if you like the solution.

**Comment by genismauri** [comment]
Looks ok!
