### ISSUE TITLE
Need to manage status of organization

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#178]
Now organization get created in 2 way:
from autoregistration = pending
from admin action = validated

status are:
- pending
- validated
- retired

We need feature to manage status by admin only

**Comment by gioppoluca** [comment]
@genismauri validate and than assign to @xeviscc

**Comment by genismauri** [comment]
from autoregistration = pending > **YES**
from admin action = validated > **YES**

status are:
- pending > **YES**
- validated > **YES**
- retired > Do we need that?

**Comment by gioppoluca** [comment]
what happens when a service provider goes away?
do we delete all the things, do we need to keep stuff for a certain period for legal reasons?

**Comment by genismauri** [comment]
Our idea:

if SP goes away (terminates contract with CO):
- grace period (1 week?) to renew/back-up.
- after that, we delete application not to have innecesary costs.
- but we keep the account so if SP returns after X time, it doesn't have to start from scratch.

Since the validation process should be updated periodically (organization need to demonstrate yearly that are paying the taxes via the third document requested) we don't need that "retired" status. if not validated > pending

**Comment by gioppoluca** [comment]
Organization stastus will be:
- to validate (can go to "validated") [no service provider only subscriber]
- validated (can go to "to validate" and to "retired") (all org)
- retired (can go to "validated") (all org)

This apply to all opreganizations with described behaviour:

For a retired subscriber: any cloud account needs to be removed, all deployments need to be removed all monitoring will be deleted.
For retired SP: all cloud accounts will be removed (notice that we do not remove deployment since they could be on other cloud accounts and we do not care as CloudOpting if there are still any around)

**Comment by genismauri** [comment]
- to validate (can go to "validated") [no service provider only subscriber] > We see necessary to have the SP also validated: we don't want SP that have economic trouble, that may let down a SS and may leave CloudOpting with on-going subscriptions.
- validated (can go to "to validate" and to "retired") (all org) > **OK**
- retired (can go to "validated") (all org) > **OK**

Also, can we find another wording for "to validate"? It's too similar, why not: "pending"?
Or playing with tag colours? "to validate" in yellow; "validated" in green?

**Comment by gioppoluca** [comment]
Agree "to validate" will become "pending"

**Comment by xeviscc** [comment]
Added values into PROD and DEV databases.
