### ISSUE TITLE
document for organization validation

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#182]
from #172 
First, **Organisation validation**
- Legal Entity Form.
- A copy of an official document legally establishing the organisation.
- A copy of an official document proving the VAT number.

**Comment by gioppoluca** [comment]
Specify whe these documents need to enter the system please

**Comment by genismauri** [comment]
In the "Organisation Profile" > 3 fields to add/upload the docs.

**Comment by gioppoluca** [comment]
after the registration?

**Comment by genismauri** [comment]
Yes

**Comment by genismauri** [comment]
@gioppoluca Based on the Catalogue vs CRM conversations, is this issue necessary any longer?

**Comment by guidospadotto-profesia** [comment]
I would close this issue if it is no more relevant. @gioppoluca what do you think?

**Comment by genismauri** [comment]
I believe this can be closed.
