### ISSUE TITLE
legal documents for subscribtion

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#183]
from #172 
Third, **Service subscription**
- Contract CloudOpting-Service Subscriber (last signed version uploaded, process carried out offline)

**Comment by gioppoluca** [comment]
Please track here the lifecycle of this document who produces it when and where and why you need it in the system

**Comment by genismauri** [comment]
WHO: CloudOpting sends contract A to SS, who sings it and send it back to CO (outside catalogue). CO uploads the contract A to "WHERE"

WHEN: After CO wins the tendering process of Service A

WHERE: In the SS Profile > Service Profile A > Contract A

WHY: The contract A must be available at any moment for both parties, keeping the lastest version.

**Comment by gioppoluca** [comment]
tendering process???
We are adding things in a too fast low analized way we need to better understand all the process.
This was a catalogue and we designed from the beginning as being able to do that: deploy on cloud.
Than added some more features, but now there are concepts that I think cannot be solved just by a couple of docs (if is like that the catalogue is not the place, it can be in the CRM of the entities).
You are mapping the CRM of a company and the catalogue will never be this.

**Comment by genismauri** [comment]
The whole process is carried out outside the catalogue, a CRM would track all the workflow.
We are just proposing to have a place in which a signed PDF contract can be stored in the SS profile.

**Comment by guidospadotto-profesia** [comment]
Why don't we just keep all the documents in an external system and simply embed hyperlinks to them in the service description? That should cover all our requirements without having us to re-implement a CRM.

**Comment by gioppoluca** [comment]
These documents are managed in the CRM systems of all the actors, there is no point to keep them here.
Any implementation will be lacking of the most basic features or will require a development effort beyond the one we have.
