### ISSUE TITLE
cloud account table content in DB crypted

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#185]
We need to understand the options for encrypting the column content in this table since its the place where we store the cloud account data that is the one that represent money

**Comment by gioppoluca** [comment]
There are many options (doing the enc/decr in java before saving OR cypher the DB column).
Let us discuss it

**Comment by gioppoluca** [comment]
Client-Side Encryption

    If the system administrator cannot be trusted, it is necessary for the client to encrypt the data; this way, unencrypted data never appears on the database server. Data is encrypted on the client before being sent to the server, and database results have to be decrypted on the client before being used.

Encryption For Specific Columns

    The /contrib function library pgcrypto allows certain fields to be stored encrypted. This is useful if only some of the data is sensitive. The client supplies the decryption key and the data is decrypted on the server and then sent to the client.

    The decrypted data and the decryption key are present on the server for a brief time while it is being decrypted and communicated between the client and server. This presents a brief moment where the data and keys can be intercepted by someone with complete access to the database server, such as the system administrator.

**Comment by guidospadotto-profesia** [comment]
@gioppoluca Please check this important warning (source: http://www.jasypt.org/hibernate.html# )

> But encryption sets a limitation on your Hibernate usage: security standards establish that two different encryption operations on the same data should not return the same value (due to the use of a random salt). Because of this, none of the fields that are set to be encrypted when persisted can be a part of a WHERE clause in your search queries for the entity they belong to

We HAVE to be sure that all the attributes we want to encrypt are not used for selection of records (that is, in "WHERE" clauses, as stated above).

**Comment by gioppoluca** [comment]
Yes we need to crypt the api_key and the secret_key in the table and we never do a where clause on those we just write and read them.
Those are the only 2 columns we need to cypher

**Comment by guidospadotto-profesia** [comment]
Done
