### ISSUE TITLE
Remove SNAPSHOT dependencies from the pom

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#188]
Please remove SNAPSHOT dependencies, if possible, from the Maven Project Object Model.
They might break the build without any modification in our code (it has already happened).

If it is NOT possible, please leave an xml comment right beside the dependency, so that we know why we depend on it.

**Comment by guidospadotto-profesia** [comment]
Any news?

**Comment by xeviscc** [comment]
@cpopsa Did you manage to get rid of all SNAPSHOT dependencies? Could you give us an update on that issue?
