### ISSUE TITLE
alter columns in application table

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#189]
We need to add:

service_price = string
platform_price = string
sizing = linked to a sizing table to be created

As usual modify the java and both DB

**Comment by xeviscc** [comment]
@gioppoluca It would be more efficient to create a table related with appliaction called Pricing with all this information? Then an application could have more than one price in the future.

**Comment by ciprianpavel** [comment]
What is the Use Case of having more prices? This is needed in order to deign the data model right from the beginning.

**Comment by gioppoluca** [comment]
this is for answering to the need expressed in WP5.
They requested a price for the service and a price for the platform
all the application will have to have their price and even when we will add another entity to group applications we will have each element of the group having its price.
This is to give a quick answer.
I vote against having a dedicated table since I do not like to have a too complex pricing stuff unless we think is usefull, but for sure a dedicated table could be interesting, but let us keep it simple.

**Comment by gioppoluca** [comment]
@cpopsa mind that I was mistaken the application_subscriber_mail has to stay there, my fault sorry.

**Comment by cpopsa** [comment]
Please describe the sizing table

**Comment by gioppoluca** [comment]
Sizing table is a table with:
id (sequence)
Sizing (String)

much like a status, just for not writing the sizing with all different words.

**Comment by cpopsa** [comment]
What are the possible values for sizing?

**Comment by gioppoluca** [comment]
Still not final but
Big city
Small city
Region




lunedì 1 febbraio 2016, 11:48 +0100 da cpopsa  <notifications@github.com>:

**Comment by MiquelBonetSDG** [comment]
The previous months we have been working with the following sizing for Public Entities:
- Small (1 to 20,000 citizens)
- Medium (20,001 to 100,000 citizens)
- Large (100,001 to 500,000 citizens)
- Extra large (more than 500,000 citizens)

Is it possible to do it like this?

**Comment by gioppoluca** [comment]
IT will be a string so whatever we like is possible 


lunedì 1 febbraio 2016, 13:08 +0100 da Miquel Bonet  <notifications@github.com>:

**Comment by cpopsa** [comment]
Done. The table with sizes is called application_size and contains values: Small, Medium, Large, Extra large
