### ISSUE TITLE
Screens on the UI

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#190]
I have been looking into the UI and there are some screens that are deprectaed or useless after a time of changeng thinks and developing.

- The Taylor Service screen now is the Form Generation Screen. We will delete the old one and change the name of the new one.
- The Add/Deploy Service screen, is not used anymore. The functionalities are in the Instances list screen. Should we delete it or give it a try from some place?
- The Servie Logs has been absorved by the Service Monitoring?
- The Service Management should be a place to Manage the Monitoring, the Logs , to see the details of a service, and also to perform some actions. Maybe it is a mix of "Add/Deploy screen" plus "Service Monitoring" plus "Service Logs".

I will need the opinion from all WP2 and WP5 teams.
@CloudOpting/fullteam @CloudOpting/sdggroup

**Comment by xeviscc** [comment]
Is the Button Screen still useful?

**Comment by genismauri** [comment]
Which screens are we defining here? Just the SP? Or starting from the Registration/Sing in screens?

**Comment by xeviscc** [comment]
We are not defining flows here.
Some of the screen seems to be deprecated and its functionalities now are in other screens.

**Comment by genismauri** [comment]
So from our point of view, OK.
Workflows and proposed screens in #127

**Comment by xeviscc** [comment]
Non needed screens will be deleted in future commits it is not mandatory to delete it from the platform right away.

**Comment by xeviscc** [comment]
I only left the "Button Screen"
