### ISSUE TITLE
Problems detected in docker-component

### ISSUE THREAD

**Issue by jmcerpa** [CloudOpting/cloudopting-manager#192]
Problems in deploy, build image with image base and context with group name

**Comment by gioppoluca** [comment]
Not understand

**Comment by jmcerpa** [comment]
when you create the context, you can't use a group name, you only can use the default name.
you can't build a image with image base + puppetmanifest.
when docker-component want deploy, he use a wrong token.
when you use isCompositionDeployed, return true every times.
I also want to add some functionality.
I'm making changes and preparing new tests and find new bugs.

**Comment by jmcerpa** [comment]
I fixed the problems and I added new methods.

**Comment by xeviscc** [comment]
I think you introduced an error:

In compilation this error is thrown.

```console
[ERROR] /home/debian/cloudopting-manager/bpmn-component/src/main/java/eu/cloudopting/bpmn/tasks/deploy/DeployDockerBuild.java:[43,50] method buildDockerImage in class eu.cloudopting.docker.DockerService cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/debian/cloudopting-manager/bpmn-component/src/main/java/eu/cloudopting/bpmn/tasks/deploy/DeployRunr10k.java:[28,53] method newContext in class eu.cloudopting.docker.DockerService cannot be applied to given types;
  required: java.lang.String,java.lang.String
  found: java.lang.String
  reason: actual and formal argument lists differ in length
```

**Comment by gioppoluca** [comment]
You broke the dependant projects?
Please either you commit a working component or you contact some of us alerting that you are committing a breaking part

**Comment by gioppoluca** [comment]
@jmcerpa please:
1) do a complete build before committing you cannot leave people with a broken repo, we will have to invest time in fixing things you broke
2) before making changes in the docker component that is used by the orchestrator you have always have a call with me because we need to understand the consequences in the whole project
Thanks

**Comment by xeviscc** [comment]
Again the same error on commit https://github.com/CloudOpting/cloudopting-manager/commit/7597f0a85aa93628ff4fbae6b32290ae4ef02dbe
