### ISSUE TITLE
PUT /api/customization should allow to save Cloud Accounts

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#194]
We need to be able to set a cloud account for a particular customization.

**Comment by xeviscc** [comment]
With setting the id of the cloud should be enough.

```json
{
  "idApp": "",
  "user": "",
  "organization": "",
  "type": "",
  "customizationId": "",
  "status": "",
  "payService": false,
  "payPlatform": false,
  "isTrial": false,
  "trialEndDate": "",
  "cloudAccountId": ""
}
```

Another question.
**If we send a PUT with only like the following example, it will only modify the cloudAccount?**

```json
{
  "idApp": "",
  "cloudAccountId": ""
}
```

**Comment by xeviscc** [comment]
Needed for #163

**Comment by cpopsa** [comment]
Done. If you send a PUT with 
{
  "id": "",
  "cloudAccountId": ""
}

id - represents the customization id
cloudAccountId - id of a cloud account

only the cloud account will be set.
