### ISSUE TITLE
alter application columns

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#196]
In the application table the columns application_ps_mail  and application_subscriber_mail needs to be text and not avarying.
We need to write long text here

**Comment by cpopsa** [comment]
Done

**Comment by guidospadotto-profesia** [comment]
Just for the sake of clarity: is application_subscriber_mail the mail that subscribers can use to communicate with the service provider? @gioppoluca

**Comment by gioppoluca** [comment]
Yes those 2 columns keep the freemarker template 




lunedì 1 febbraio 2016, 12:03 +0100 da Guido Spadotto  <notifications@github.com>:
