### ISSUE TITLE
Verify usage of encryption for properties

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#197]
At the moment we have properties like password for various components like Db etc in clear in git and also will be in clear in the property file.
Please look at the following project and see if it can help solving the problem

https://github.com/ulisesbocchio/jasypt-spring-boot

**Comment by gioppoluca** [comment]
Un tutorial ben fatto
https://www.ricston.com/blog/encrypting-properties-in-spring-boot-with-jasypt-spring-boot/

**Comment by gioppoluca** [comment]
http://www.programcreek.com/java-api-examples/index.php?source_dir=github-cla-integration-master/src/main/java/com/gopivotal/cla/repository/RepositoryConfiguration.java
https://github.com/pivotalsoftware/github-cla-integration/blob/master/src/main/java/com/gopivotal/cla/repository/RepositoryConfiguration.java

Altri link con tranci di codice utile

**Comment by guidospadotto-profesia** [comment]
Implemented in 76d8340
Remember to export the JASYPT_ENCRYPTOR_PASSWORD encironment variable with the value provided in the mailing list.
