### ISSUE TITLE
Activiti Explorer and Spring Boot

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#20]
From the following post:
http://forums.activiti.org/content/activiti-explorer-and-springboot
It seems that it is not yet possible to have the Activiti Explorer (web)app running within a Spring Boot application. As a consequence, all the User Interface for interacting with process instances is not available.

This is a major draw-back as it restricts the use of Activiti process to "batch-like" processes (no user interaction, all variables defined at "Process Invocation Time", rest APIs with potentially dozens of input parameters, ... ).

**Comment by gioppoluca** [comment]
The same things that can be done by Activiti explorer can be done through rest API, but we do not need it too much
Let have a quick call on it

**Comment by gioppoluca** [comment]
issued solved and applyed to code
