### ISSUE TITLE
Image of the service not taken from jackrabbit

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#203]
Created new service added an image.
Image is in jackrabbit, but not showed in catalog.

Service is aSweden

**Comment by gioppoluca** [comment]
Related to #204

**Comment by guidospadotto-profesia** [comment]
Services published after commit 87da458 should have all references in place. Please check again.

**Comment by guidospadotto-profesia** [comment]
@xeviscc I save the path of the Logo image in the "applicationLogoReference" attribute.

**Comment by xeviscc** [comment]
@guidospadotto-profesia @gioppoluca The Logo is the image that we want to show in the Catalogue and in the detail of the Service?

**Comment by guidospadotto-profesia** [comment]
I think so, yes.

**Comment by xeviscc** [comment]
Done.
