### ISSUE TITLE
files added to the service are not persisted on the DB

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#204]
Both the image and the files of the service are not placed (as reference in jackrabbit) in the DB.

We need a dedicated column in the application table for the image and keep the application_meadia for all other files since I cannot otherwise distinguish the image from other files and could get a mess otherwise

**Comment by gioppoluca** [comment]
please start fixing the persisting of the files than look after the image

**Comment by guidospadotto-profesia** [comment]
Depends on resolution of #209

**Comment by xeviscc** [comment]
Needed for #203

**Comment by guidospadotto-profesia** [comment]
I am adding the column myself. Will need to update persistents and DB tables, then, regenerate the script. (Hopefully, not by hand)

**Comment by guidospadotto-profesia** [comment]
Also, a SINGLE Logo will be supported, please update the UI so that you cannot add several service images @xeviscc

**Comment by xeviscc** [comment]
It already only allows one file.

**Comment by guidospadotto-profesia** [comment]
Fixed in 87da458
