### ISSUE TITLE
add image_ref column to the application table

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#205]
We need to keep the reference to the image placed in jackrabbit so we need a string column in the application table.

As usual on both Db + java 

related to #204

**Comment by xeviscc** [comment]
Could you also add it into the following script in order to have it up to date: https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/postgres_cloudopting_database_initial_script.sql

**Comment by cpopsa** [comment]
Done
