### ISSUE TITLE
Publishing form for service needs to be updated to new fields

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#208]
We added a lot of new info in the application table and we need to update the GUI for it.

**Comment by xeviscc** [comment]
We have the following tables directly related with applications:
- application_media
  - id
  - application_id
  - media_content
- application_size
  - id
  - size (Small, Medium, Large, Extra large)
- applications_tags
  - application_id
  - tag_id
- tags
  - id
  - tag
- applications
  - id **DB: AUTOMATIC**
  - application_name **UI: First screen of the wizzard of publication**
  - application_description **UI: First screen of the wizzard of publication**
  - application_tosca_template **SERVER: Setted the Jackrabbit path after uploading the TOSCA archive**
  - application_version **SERVER: AUTOMATIC on update**
  - status_id **SERVER: Managed by the BPMN**
  - organization_id **UI: Assigned on the creation of the application**
  - application_tosca_name  **UI: First screen of the wizzard of publication**
  - application_process **SERVER: BPMN**
  - short_description 
  - application_subscriber_mail 
  - application_sp_mail 
  - application_is_tryable 
  - terms
  - service_price
  - platform_price
  - size_id

Should we create fields for all the columns from short_description to size_id?

**Comment by gioppoluca** [comment]
No we need to ADD the following fields to the UI in the edit:
short_description (+)
terms (+)
application_subscriber_mail
application_sp_mail
application_is_tryable (+)
service_price (+)
platform_price (+)
size_id (+)

The terms in the catalogue need to be accepted implicitly by marking a checkbox before pressing the subscribe (until you mark the accept subscribe button will not activate)
Also in the catalogue fields marked with + needs to be used

**Comment by xeviscc** [comment]
@gioppoluca OK, I will add these new fields, but how can in the publication of a service the SP know the mail of the SUBSCRIBER. "application_subscriber_mail" ?

**Comment by xeviscc** [comment]
I see in the database that this mails are templates. Ok. Gotcha!
