### ISSUE TITLE
Impossible to persist media content

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#209]
When publishing a new service, I add some Application medias in the second step, but when I try to persist them in the "application_media" table, I get this runtime error:

Hibernate: insert into public.application_media (application_id, media_content, id) values (?, ?, ?)
[WARN] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42804
[ERROR] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: column "media_content" is of type character varying[] but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 86

What I'm trying to save is a Java String, as per
definition of "mediaContent" in ApplicationMedia.java

**Comment by xeviscc** [comment]
Needed for #204

**Comment by xeviscc** [comment]
In my opinion there is a mistake in the definition of the column in the database. The [] shouldn’t be there. 
It expects an array, and we provide an String.

**Comment by guidospadotto-profesia** [comment]
I have changed the type of the column to "text", this should fix this issue.
Isn't there a way to get the updated DDL / APIs by reverse-engineering the current status of the DB?

**Comment by xeviscc** [comment]
Could you also add it into the following script in order to have it up to date: https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/postgres_cloudopting_database_initial_script.sql

**Comment by cpopsa** [comment]
It is fixed
