### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by j-fuentes** [CloudOpting/cloudopting-manager#21]
In docker-component, for example, could occur the following:

- BPMN engine calls `docker.build.getInfo("5jg90dfjn54")` in order to obtain information about the build process referenced by the token.

- Docker commander receives the request and sends a response with status code `404 not found` because this build process doesn't exists.

At the moment I was thinking in `getInfo()` throwing a `DockerError` exception with the message `"No build process asociated with the token."` and BPMN engine cathing it but I am not sure if this is the way. I mean, I don't know if the BPMN engine can take an exception as the output from a request.

**Comment by gioppoluca** [comment]
BPMN can get exceptions

**Comment by j-fuentes** [comment]
Ok.
Thanks you.
