### ISSUE TITLE
add field is_for_tryal to cloud_account table

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#212]
We need to manage in case of multiple cloud accounts for an org which one is the one used for the tryal (try before buy)
The new column is a boolean.
All DB and JAVA

**Comment by xeviscc** [comment]
Should it be "trial".
I searched it in the oxford dicionary and it does not appear there.
http://www.oxforddictionaries.com/spellcheck/english/?q=tryal

**Comment by gioppoluca** [comment]
Yes LOL





----Messaggio originale----

Da: Xavier Cases Camats <notifications@github.com>

Data: 09/02/2016 10.22

A: "CloudOpting/cloudopting-manager"<cloudopting-manager@noreply.github.com>

Cc: "Luca Gioppo"<gioppoluca@libero.it>

Ogg: Re: [cloudopting-manager] add field is_for_tryal to cloud_account table (#212)




Should it be "trial".

I searched it in the oxford dicionary and it does not appear there.

http://www.oxforddictionaries.com/spellcheck/english/?q=tryal

**Comment by cpopsa** [comment]
Done
