### ISSUE TITLE
Create new table for zabbix monitoring

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#216]
I reconsidered that is better to have a table also for zabbix data is too messy to recover info dynamically.

New table will be:
customization_monitoring_zabbix

Columns:
id
customization_id (reference to the customization table)
host (string)
item (string)
history (string)
sortfield (string)
limit (integer)
description (string)
chart_type (string)
unit (string)

As always Db and java

**Comment by cpopsa** [comment]
Done
