### ISSUE TITLE
DockerService interface

### ISSUE THREAD

**Issue by j-fuentes** [CloudOpting/cloudopting-manager#22]
Could you take a look to this commit https://github.com/CloudOpting/cloudopting-manager/commit/3cf1696bac4d40d987a5c186e648bf9877af57f3?

I think that it is a better way to provide a pure java interface and abstract BPMN logic from tokens and this stuff.

**Comment by gioppoluca** [comment]
The DockerService is a singleton by definitio of injection of spring.
This means that each sequent calls will be done on the same instance if we do not have the token the user2 could get the answer of the user1 also we as a java application decided we want that the single process will be serial but we could have more than 1 process running at time so the python component will be called to do more than one build at time on different folders so you need to be sure to give the correct answer to the correct user.
For sure the python API will have to use a token.
this has to be passed down to all the invoking chain.
