### ISSUE TITLE
Get image ID on api/application/{idApp}/{idProcess}/file POST

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#222]
When an upload is performed the ID of the file uploaded should be sended as a response in order to be able to delete it.

**Comment by xeviscc** [comment]
Needed for #202

**Comment by guidospadotto-profesia** [comment]
There is no id in JackRabbit, just the path to the file in the repository.

**Comment by xeviscc** [comment]
We have to think the way to delete an updated image. Maybe with the full URL of the image stored in jackrabbit?

**Comment by guidospadotto-profesia** [comment]
Yes, that's the way.

**Comment by xeviscc** [comment]
So the full URL will be needed in the response to be able to delete it in the future. We also will need an endpoint to delete images sending the full path.

**Comment by guidospadotto-profesia** [comment]
Implemented the DELETE api/jr/img endpoint in 76550f2 .

**Comment by xeviscc** [comment]
We also need to Get image FULL JACKRABBIT URL on api/application/{idApp}/{idProcess}/file POST response.
If we want to edit the service in the first screen when you are doing the publication for the first time you wont be able to do it without the FULL JACKRABBIT URL.

**Comment by xeviscc** [comment]
In my opinion to DELETE a file it shold be an endpoint similar to
```
api/application/{idApp}/{idProcess}/file POST
```

Something like the following
```
api/application/{idApp}/file/{fullJackrabbitPath} DELETE
```

in order to be coherent with endpoints and also to manage the deletion of the link into the applications table

**Comment by guidospadotto-profesia** [comment]
The {fullJackrabbitPath} parameter will be something like "http://path.to/jackrabbit/repository/Filename.extension". Is it possible to map the URLs in the mapping?

**Comment by xeviscc** [comment]
Yes the full path will be something like that.
What do you mean with the mapping?

**Comment by xeviscc** [comment]
@guidospadotto-profesia Is this already implemented (POST/DELETE) ? Issue #73 depends on it.

**Comment by guidospadotto-profesia** [comment]
@xeviscc The ActivitiDTO return object contains an attribute named "jrPath" that should contain the JackRabbit path of the latest uploaded file. The problem is when we have multiple files uploaded.

**Comment by xeviscc** [comment]
Ok, one request at a time is done, never more than 1 file is send in terms of requests.

**Comment by guidospadotto-profesia** [comment]
It was implemented as:

> @RequestMapping(value = "/jr/img", method = RequestMethod.DELETE)
> public final Boolean deleteJcrImage(@RequestParam("jcrPath") String jcrPath)

**Comment by xeviscc** [comment]
OK, so the issue is solved, right? Could you close it?

**Comment by guidospadotto-profesia** [comment]
I would like you to test it. I can't at the moment as I am travelling.

**Comment by xeviscc** [comment]
Ok, will test it!
