### ISSUE TITLE
Some parameters on endpoints should be numbers, not strings

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#223]
For example when you GET an application with endpoint "/api/application/{idApp}

In the following example can be seen that they are Strings.
```json
  "servicePrice": "",
  "platformPrice": "",
```

![image](https://cloud.githubusercontent.com/assets/10829055/13080282/4d551730-d4c8-11e5-8fb5-0a76762f8ce1.png)

**Comment by xeviscc** [comment]
Needed for #73

**Comment by gioppoluca** [comment]
No those are strings since we allow people to write things like.

"300 €/month"
We really do not care and do not want to do any calculation.
