### ISSUE TITLE
Failed to execute /api/application/listunpaginated on rest-component

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#23]
I tryed to call the following endpoint with bad results.

Could you please have a look at it?

## Request URL

> http://cloudopting1.cloudapp.net:8081/cloudopting/api/application/listunpaginated

## Response body

> {
>   "timestamp": 1432634836223,
>   "status": 500,
>   "error": "Internal Server Error",
>   "exception": "org.springframework.dao.InvalidDataAccessResourceUsageException",
>   "message": "Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"
> }

## Response Code

> 500

## Response Headers

> {
>  "Date": "Tue, 26 May 2015 10:07:16 GMT",
>  "Server": "Apache-Coyote/1.1",
>  "Proxy-Connection": "Keep-Alive",
>  "Content-Type": "application/json;charset=UTF-8",
>  "Transfer-Encoding": "chunked",
>  "X-Cache": "MISS from 10.86.143.197",
>  "X-Application-Context": "application:dev:8080"
>}

![image](https://cloud.githubusercontent.com/assets/10829055/7810200/4d41bffe-03a0-11e5-8deb-09bbb7c65787.png)

**Comment by xeviscc** [comment]
According Daniel, the database has changed, so the rest-component should be changed and deployed again to solve the issue.

**Comment by gioppoluca** [comment]
Please check if this applyes or not and close if possible

**Comment by xeviscc** [comment]
The bug has been solved.
