### ISSUE TITLE
DISABLE automatic deployment of process definitions OR use a local copy of the DB

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#235]
We need to disable the automatic deployment of process definitions to the DB, otherwise any change done by any developer (even in private branches) will impact all users.

Why can't we just use local copies of the DB, like any project since the dawn of computer science?

@gioppoluca @xeviscc @cpopsa

**Comment by xeviscc** [comment]
I prefer not to use local database. 
Because of:
* It is a source of problems because of diferences between them. 
* It is also a waist of resources I need. 
* Annoyance of installing another piece of software.

**Comment by xeviscc** [comment]
Do we have to keep it open?

**Comment by guidospadotto-profesia** [comment]
No
