### ISSUE TITLE
publish UI does not help understand what you have to do

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#236]
In the publish UI the breadcrumbs on top does not help understand what to do.
Sometimes even myself forget if have to place the tosca file in step 2 or 3.
Can we change the text to something more helpful like:
- insert service metadata
- add files required in the tosca file
- add the tosca file
- submit the service

See image in #234

**Comment by xeviscc** [comment]
@dacafo David, could you please check it with Aurora? If you have any doubt, call me.

**Comment by dacafo** [comment]
I've talked to Aurora and told me to transfer to Xavi Riera because this is not an issue of design, it is an issue of content.
