### ISSUE TITLE
compilation error AGAIN

### ISSUE THREAD

**Issue by ignasijr** [CloudOpting/cloudopting-manager#243]
MacBook-MacBook-Pro-de-Ignasi:cloudopting-manager ignasi$ cd rest-component/;JASYPT_ENCRYPTOR_PASSWORD=****** mvn spring-boot:run ; cd ..
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rest-component 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.2.8.RELEASE:run (default-cli) > test-compile @ rest-component >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ rest-component ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rest-component ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 26 resources
[INFO] Copying 30 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ rest-component ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 30 source files to /Users/ignasi/Documents/cloudopting-manager/rest-component/target/classes
[INFO] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java: /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java uses or overrides a deprecated API.
[INFO] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/ApplicationResource.java: /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/ApplicationResource.java uses unchecked or unsafe operations.
[INFO] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/ApplicationResource.java: Recompile with -Xlint:unchecked for details.
[INFO] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[5,46] cannot find symbol
  symbol:   class ElasticData
  location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[14,13] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[34,12] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[38,26] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[26,46] cannot find symbol
  symbol:   class ElasticData
  location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[27,46] cannot find symbol
  symbol:   class ElasticGraphData
  location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[99,26] cannot find symbol
  symbol:   class ElasticGraphData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[27,34] cannot find symbol
  symbol:   class ZipDirectory
  location: package eu.cloudopting.tosca.utils
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[38,9] cannot find symbol
  symbol:   class ZipDirectory
  location: class eu.cloudopting.web.rest.CytoscapeController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[102,27] cannot find symbol
  symbol:   class ElasticGraphData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[149,115] incompatible types: java.lang.Long cannot be converted to java.lang.String
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[153,17] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[153,45] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[157,25] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[157,46] cannot find symbol
  symbol:   class ElasticData
  location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[44,59] cannot find symbol
  symbol:   method getEdgeTypeList()
  location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[54,42] cannot find symbol
  symbol:   method getEdgeTypeJsonList()
  location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[62,59] cannot find symbol
  symbol:   method getNodeTypeList()
  location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[70,42] cannot find symbol
  symbol:   method getNodeTypeJsonList()
  location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[99,29] cannot find symbol
  symbol:   method writeToscaDefinition(org.json.JSONObject,java.lang.String)
  location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[INFO] 20 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.685 s
[INFO] Finished at: 2016-02-24T12:07:14+01:00
[INFO] Final Memory: 49M/272M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project rest-component: Compilation failure: Compilation failure:
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[5,46] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[14,13] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[34,12] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/dto/ElasticGraphDTO.java:[38,26] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.dto.ElasticGraphDTO
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[26,46] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[27,46] cannot find symbol
[ERROR] symbol:   class ElasticGraphData
[ERROR] location: package eu.cloudopting.monitoring.elastic.data
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[99,26] cannot find symbol
[ERROR] symbol:   class ElasticGraphData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[27,34] cannot find symbol
[ERROR] symbol:   class ZipDirectory
[ERROR] location: package eu.cloudopting.tosca.utils
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[38,9] cannot find symbol
[ERROR] symbol:   class ZipDirectory
[ERROR] location: class eu.cloudopting.web.rest.CytoscapeController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[102,27] cannot find symbol
[ERROR] symbol:   class ElasticGraphData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[149,115] incompatible types: java.lang.Long cannot be converted to java.lang.String
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[153,17] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[153,45] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[157,25] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/MonitoringController.java:[157,46] cannot find symbol
[ERROR] symbol:   class ElasticData
[ERROR] location: class eu.cloudopting.web.rest.MonitoringController
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[44,59] cannot find symbol
[ERROR] symbol:   method getEdgeTypeList()
[ERROR] location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[54,42] cannot find symbol
[ERROR] symbol:   method getEdgeTypeJsonList()
[ERROR] location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[62,59] cannot find symbol
[ERROR] symbol:   method getNodeTypeList()
[ERROR] location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[70,42] cannot find symbol
[ERROR] symbol:   method getNodeTypeJsonList()
[ERROR] location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] /Users/ignasi/Documents/cloudopting-manager/rest-component/src/main/java/eu/cloudopting/web/rest/CytoscapeController.java:[99,29] cannot find symbol
[ERROR] symbol:   method writeToscaDefinition(org.json.JSONObject,java.lang.String)
[ERROR] location: variable toscaService of type eu.cloudopting.tosca.ToscaService
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
MacBook-MacBook-Pro-de-Ignasi:cloudopting-manager ignasi$

**Comment by xeviscc** [comment]
You have to first compile the application by executing the following command on the root of the project:

```console
mvn clean install
```

**Comment by xeviscc** [comment]
@ignasijr Have you been able to start the platform?
