### ISSUE TITLE
"Privacy Policy" do not exists.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#249]
"Privacy Policy" do not exists.

Some text has to be written in order to state our privacy terms.

**Comment by genismauri** [comment]
[WP5_Privacy Policy_v1.1.docx](https://github.com/CloudOpting/cloudopting-manager/files/174093/WP5_Privacy.Policy_v1.1.docx)

Here you are a proposed text.

**Comment by genismauri** [comment]
When clicking on "Privacy Policy" link in the Catalogue the text isn't shown.

**Comment by xeviscc** [comment]
It is in development. It will be there on the next release.
