### ISSUE TITLE
"Terms of Use" do not exists

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#250]
"Terms of Use" do not exists.

Some text has to be written in order to state our terms of use.

**Comment by genismauri** [comment]
[WP5_Terms and Conditions_v1.1.docx](https://github.com/CloudOpting/cloudopting-manager/files/174097/WP5_Terms.and.Conditions_v1.1.docx)

Here you are a proposed text (draft version), that is going to be updated in the upcoming months.
Notice that some links need to be updated (references between Terms and Policies, for instance).
When necessary, it was added as comment in the document, please check it out.

**Comment by genismauri** [comment]
When clicking on "Terms of Use" link in the Catalogue the text isn't shown.

**Comment by xeviscc** [comment]
It is in development. It will be there on the next release.

**Comment by genismauri** [comment]
Then, let's keep that opened to keep track of the issue.

**Comment by xeviscc** [comment]
In production.
