### ISSUE TITLE
add spring dev profiles

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#252]
We need to be able to run project in dev as before and than compile for production without having to manually change the pom each time.
Daniel suggested a solution please apply it and document how will have to be used

**Comment by xeviscc** [comment]
We need an update on that! It is urgent!

**Comment by cpopsa** [comment]
I downgraded the spring-boot-maven-plugin version from 1.3.2.RELEASE to 1.3.1.RELEASE in order to be possible to run the app with mvn spring-boot:run. No other configuration is needed.

**Comment by gioppoluca** [comment]
There are still problems.
I cannot use the Spring IDE since there are lot of errors due to the fact it does not find stuff

**Comment by cpopsa** [comment]
Eclipse IDE problem. Solved
