### ISSUE TITLE
If no monitoring defined on DB all appear to be selected

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#254]
When you access Service Monitoring from an instance that has no monitoring assigned it gets a list of everything.

**Comment by gioppoluca** [comment]
This should not happen.
The tables should have the proper info and this is just a dev quirk.
Will check to manage in any case the empty info

**Comment by xeviscc** [comment]
From the UI perspective we could not know if the selected instance has or not info to show.

**Comment by gioppoluca** [comment]
We should.
The status of the customization has to be used
If not deployed monitoring and stop or start Cannot be pressed 
--
Inviato da Libero Mail per Android Giovedì, 10 Marzo 2016, 08:51AM +01:00 da Xavier Cases Camats < notifications@github.com> :
