### ISSUE TITLE
cannot see instances list of a service

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#257]
I go to the service list.
press list instances
come to the page and get error
 An error occurred. Wait a moment and try again, if problem persists contact the administrator 

{"message":"Bad request","exception":"Could not write content: Infinite recursion (StackOverflowError) (through reference chain: eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.PersistentSet[0]->eu.cloudopting.domain.Customizations[\"cloudAccount\"]->eu.cloudopting.domain.CloudAccounts[\"customizationss\"]->org.hibernate.collection.internal.Per

**Comment by gioppoluca** [comment]
Do not know if the error is due to the missing idapp or what

**Comment by gioppoluca** [comment]
@cpopsa take a look at this as it could be related to something on DB or other

**Comment by ignasijr** [comment]
same problem happens to me:

**Comment by cpopsa** [comment]
Fixed
