### ISSUE TITLE
See instances

### ISSUE THREAD

**Issue by ignasijr** [CloudOpting/cloudopting-manager#258]
I have published a Service: aaa, and whenever I try to subscribe I click on See instances:

![captura de pantalla 2016-03-08 a les 12 27 28](https://cloud.githubusercontent.com/assets/10829057/13600451/2f173f48-e529-11e5-8951-0e66b28db7b9.png)

**Comment by xeviscc** [comment]
It happens because you are using a user with role publisher.
In order to create an instance for an owned services you have to go to Development Menu -> Services List -> Clink New instance next to your service.

**Comment by xeviscc** [comment]
Abandoned.
