### ISSUE TITLE
Endpoint /api/application [POST] [Required for UI screen **Publish Service**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#26]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to create a new application. |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application |
| **Call Type:** | POST |
| **Request Data Type:** | application/json |
| **Request Parameters:** | Check schema |

Shema:
```json
{
  "name" : "String",
  "description" : "String"
}
```

**Comment by pdaniel-frk** [comment]
Done, need testing

**Comment by xeviscc** [comment]
The Endpoint will return an JSON object:

```json
{ 
  "applicationId" : "1594",
  "processInstanceId" : "372547"
}
```

**Comment by guidospadotto-profesia** [comment]
Is this still open?

**Comment by xeviscc** [comment]
Closing.
