### ISSUE TITLE
Check static potential problem

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#260]
At the start this is a warning:
[WARN] org.springframework.context.annotation.ConfigurationClassEnhancer - @Bean method EnableEncryptablePropertySourcesConfiguration.enable
EncryptablePropertySourcesPostProcessor is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This 
will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuratio
n class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.

**Comment by guidospadotto-profesia** [comment]
See this: https://github.com/ulisesbocchio/jasypt-spring-boot/issues/3
The author himself ignores it and suggests a workaround.
