### ISSUE TITLE
List instances does not properly work

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#261]
We need to get the list of the instances of the application.

I'm operating as service provider and I need to get only the list of customizations/instances of the chosen service/application so please check this out.

At the moment we get the whole list: is a getCustomizations

**Comment by gioppoluca** [comment]
@cpopsa check if there is also some check in the repo part

**Comment by cpopsa** [comment]
Do you need a rest endpoint to get customizations for a specific application? Something like /application/{idApp}/customizations ?

**Comment by xeviscc** [comment]
I do not need a new endpoint, I get the customizations from the selected APP.
