### ISSUE TITLE
Dynamic graph do not show correctly

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#262]
We generate graph from elasticsearch dynamically but the problem is that morris.js does not find the ele,ments since angular has not yet created them
we need to move the morris generation after we generate the element or we will have problems in visualization

**Comment by xeviscc** [comment]
This is why a timeout of 1 second was given in https://github.com/CloudOpting/cloudopting-manager/blob/master/rest-component/src/main/webapp/scripts/app/service/monitoring/monitoring.controller.js

**Comment by xeviscc** [comment]
Add something like:

```js
                    $timeout(function () {
                        $("#itemSelected").empty();
                        lineChartZabb($scope.zabbixgraph, "itemSelected");
                    }, 1000);
```
