### ISSUE TITLE
need customization activation in the monitoring page

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#266]
I need the customization_activation date passed to the monitoring page so that I can set the minimum allowed date for getting the monitoring data

**Comment by xeviscc** [comment]
You can find the instance already on the monitoring.controller.js: https://github.com/CloudOpting/cloudopting-manager/blob/master/rest-component/src/main/webapp/scripts/app/service/monitoring/monitoring.controller.js

Then you can get the activation date with:
```js
var activationDate = instance.customizationActivation;
```
