### ISSUE TITLE
The instances status retrieved from database does not match with the monitoring value.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#267]
The instances status retrieved from database does not match with the monitoring value.

The statuses of the instances should be changed according to its real status. Do not know if it is due to BPMN or TOSCA.

Could you @gioppoluca and @guidospadotto-profesia have a look at it?

**Comment by guidospadotto-profesia** [comment]
Which component manages the status transitions of services? 
During the publishing phase a service passes from the status "DRAFT" to "PUBLISHED" simply by updating the persistent value in the DB, when the Service Publisher saves the published service in the last step. If we want this event to trigger additional logic, we should maybe write a specific service that handles state transition logic and notifies "subscriber" components of state changes.

**Comment by gioppoluca** [comment]
Remeber that we have a dirty DB at the moment so some pieces could report inconsitencies due to this which instance are you referring to? @xeviscc

**Comment by xeviscc** [comment]
Yes, that is true, but I only want to assure that they are aligned. ie:

![image](https://cloud.githubusercontent.com/assets/10829055/13813867/0a3494a8-eb84-11e5-9fa3-bbeb8bc90014.png)

It is in status "Requested" but it already has monitoring according to the "brand new green pilot"

**Comment by gioppoluca** [comment]
I should have fixed the Db for that instance, BUT ...
from the image I see:
1) stop button should be disabled in the requested status
2) the customization has false in the is_trial column so demo button should be disabled aslo
3) it occurs to me that when instance is deployed deploy button will have to be disabled.

In this case this is an instance I'm using in dev to test the monitoring part so it point to a link not for sweden :D

**Comment by xeviscc** [comment]
Updated:

Test button: Always enabled
Demo button: Enabled when flag isTrial selected.
Deploy button: Enabled  when instance status is different from "Running" and "Stopped"
Start button: Enabled when monitoring status is false and instance status is "Stopped"
Stop button: Enabled when monitoring status is true and instance status is "Running"
Monitor button: Enabled when monitoring status is true
Delete button: Enabled when monitoring status is false

**Comment by xeviscc** [comment]
Closing issue as it is changing to anotherone. If further modifications needed, open another issue.
