### ISSUE TITLE
Endpoint /application/{idApp}/{processId}/file [POST] [Required for UI screen **Publish Service**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#27]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to upload files for a specific application. |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application/{idApp}/{processId}/file |
| **Call Type:** | POST |
| **Request Data Type:** | multipart/form-data |
| **Request Parameters:** | file(file), type(["promoimage", "contentlibrary", "toscaarchive"]), name(String) |

**Comment by xeviscc** [comment]
A param in the URL will be needed in order to keep track of the procces.
The param will be a QueryParam/RequestParam called "processInstanceId".

**Comment by pdaniel** [comment]
I have impolemented the server side code. The client side does not send the file to the server. Please have a look at it. I commented your code and put something else and worked. Please have a look and put all the information in the new implementation. addContentLibrary is the method i've cahnge and server side method is ApplicationResource#upload. After you resolve the problem send the task to guido. The service method is : BpmnService#upload

**Comment by xeviscc** [comment]
* Checked and fixed issues on the uploading of files in the UI.

* **TODO:** The idApp and the processID recived from the rest-component should be sended to the BPMN engine, to let it keep track of the flow.

**Comment by pdaniel** [comment]
done
