### ISSUE TITLE
There are problems browsing the catalogue with Safari. 

### ISSUE THREAD

**Issue by gcabezas** [CloudOpting/cloudopting-manager#270]
Usign safari on Mac, after browsing the catalogue for the first time, and click on a service, I cannot go back to the home screen again. Nothing is displayed, just the background image.

**Comment by ciprianpavel** [comment]
Same for IE 11 on Win 8.
Back button breaks everything.

**Comment by xeviscc** [comment]
It will be checked in the future, it is not a priority.
