### ISSUE TITLE
NETPORT is not part of the footer

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#273]
NETPORT logo is not part of footer image.

**Comment by xeviscc** [comment]
We need the logo in order to make our design colleagues

**Comment by AlexxHansson** [comment]
Logo for NetPort Science Park

![netport_science_park_logotyp_svart-web-transp](https://cloud.githubusercontent.com/assets/1838046/13913098/b7c88af8-ef43-11e5-8c92-8242a7f4d13e.png)

**Comment by xeviscc** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/10829055/14013060/5af6c39e-f1aa-11e5-918e-1b74c9841a14.png)
