### ISSUE TITLE
Endpoint /api/application/{idApp}/file/{idFile} [PUT] [Required for UI screen **Publish Service**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#28]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to update a specific file from an application |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application/{idApp}/file/{idFile} |
| **Call Type:** | PUT |
| **Data Type:** | multipart/form-data |
| **Parameters:** | file(file), name(String) |

**Comment by xeviscc** [comment]
A param in the URL will be needed in order to keep track of the procces.
The param will be a QueryParam/RequestParam called "processInstanceId".

**Comment by pdaniel** [comment]
Endpoint created, please check the endpoint in your implementation.

/application/{idApp}/{processId}/file/{fileId}

ApplicationResource#updateFile

**Comment by xeviscc** [comment]
After thinking about it. It think it does not make any sense to have an endpoint to modify a file. It should be deleted, and we could upload a new one.
