### ISSUE TITLE
Font used does not have diacritics implemented

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#280]
The used font does not display in a proper way the diacritics.
In the following image at the end of the first word (ENGLEZĂA) I have added an ASCII letter right next at the end of the word which has a diacritic

![diacritics](https://cloud.githubusercontent.com/assets/10402949/13984185/49456536-f0fd-11e5-85bb-483bb525dffd.png)

**Comment by xeviscc** [comment]
The codification of all the texts are in UTF-8.
Could you specify which characters are not displaied?

**Comment by ciprianpavel** [comment]
Ă

you can see from the image that the diacritic is not **bold**as the other letters
