### ISSUE TITLE
Wrong alignment

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#281]
Wrong alignment of icons in case of translated text

![wrongalignment](https://cloud.githubusercontent.com/assets/10402949/13984910/f1d33846-f101-11e5-8faf-02ff1b343246.png)

**Comment by xeviscc** [comment]
Texts are too long, Please use other word or something like "Monitor." for this icons.

**Comment by ciprianpavel** [comment]
Monitor is not a ROMANIAN word for that action.

**Comment by xeviscc** [comment]
As you see, I wrote a dot (.)
I do not know if it can be done in ROMANIAN, but as you can see in your screen the date is also affected for the width of the screen. These words should be as short as they can in order to help the look & feel to work properly.
