### ISSUE TITLE
Publish service page does not takes into consideration the translation

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#282]
The publish service page does not take into consideration the translated content

![publishservice](https://cloud.githubusercontent.com/assets/10402949/13985533/0de8c7c2-f106-11e5-8603-5fb495de5b5a.png)

**Comment by xeviscc** [comment]
Depends on https://github.com/CloudOpting/cloudopting-manager/issues/268

**Comment by xeviscc** [comment]
Shouold be solved.
