### ISSUE TITLE
Buttons text

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#283]
Buttons text is mixed between UPPERCASE and how is it written in translation file.
All buttons have to be checked, the example is from "new cloud account" screen.

![buttontext](https://cloud.githubusercontent.com/assets/10402949/13985765/39abb8e6-f107-11e5-96f1-b9bc8482efc1.png)

**Comment by xeviscc** [comment]
The design of the platform is done that way for all the forms. It is not a bug.

![image](https://cloud.githubusercontent.com/assets/10829055/14013215/6d1b7532-f1ab-11e5-883a-40b0d4873b52.png)

![image](https://cloud.githubusercontent.com/assets/10829055/14013235/8c1b3120-f1ab-11e5-9844-fb245a56e70c.png)

**Comment by MiquelBonetSDG** [comment]
It is not consistent to have buttons written in different ways, all buttons should have the same stile (uppercase or lowercase, not both).

**Comment by xeviscc** [comment]
Can you argument your point? We have a team dedicated to usability, I trust them.

**Comment by MiquelBonetSDG** [comment]
If there isn't a solid reason for having different styles in the buttons, it is better to have them the same (uppercase or lower case, same font, palette of colours, etc) to strengthen the CloudOpting corporative image. 

Like Amazon, who has all the buttons with black lowercase letters with a yellow background. So when you see one of this buttons you immediately relate it to Amazon. See screenshots attached:

![screenhunter_652 mar 24 15 29](https://cloud.githubusercontent.com/assets/16834188/14020110/ea07a320-f1d5-11e5-8780-a7e33a5ea08e.jpg)

![screenhunter_651 mar 24 15 28](https://cloud.githubusercontent.com/assets/16834188/14020117/eff87b42-f1d5-11e5-85df-3df948018c75.jpg)

**Comment by xeviscc** [comment]
As this is not prioritari will be done in a future release.
