### ISSUE TITLE
Filter buttons vanished

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#286]
We've thrown a step back, the 3 buttons were displayed in previous release.
It's good to have them back since it helps us to justify the choice of the vertical solutions.

**Comment by xeviscc** [comment]
Could you be a little more precise.

**Comment by genismauri** [comment]
From the homepage, the 3 buttons are not displayed now:

![image](https://cloud.githubusercontent.com/assets/16834220/13990531/0848b28c-f115-11e5-8dc6-c94c1a9f672d.png)

**Comment by xeviscc** [comment]
The buttons are not displayed because of another issue. https://github.com/CloudOpting/cloudopting-manager/issues/271
If they do nothing does not make any sense to have them here.
