### ISSUE TITLE
Problems when changing language

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#287]
If you change the language (Catalan, Romanian, Italian, etc), the following problems happen:

- The images of the main page are not displayed.
- The language section instead of "Catalan" says "Language.CA".
- The contact sections the title is "CONTACT.TITLE" instead of being in Engish or Catalan.
- If you click the buttons "sign in" or "join" they do not work.

See screenshot attached.

If we don't have the UI in the different languages or there are problems it should not be possible to choose a language.

![02_ui_change language](https://cloud.githubusercontent.com/assets/16834188/13990795/f2bd9cd8-f115-11e5-9df2-04163b1bd428.jpg)
![03_ui_change language_contact](https://cloud.githubusercontent.com/assets/16834188/13990794/f2bd02b4-f115-11e5-8e86-57bb6d7e6f63.jpg)

**Comment by xeviscc** [comment]
This is due to the following issue that has to be resolved: https://github.com/CloudOpting/cloudopting-manager/issues/268

**Comment by xeviscc** [comment]
Uploaded pictures for each language in commit  71e67ec
This images should be translated for each partner.

**Comment by xeviscc** [comment]
Should be fixed, although it might not be translated.
