### ISSUE TITLE
Format of the service features/description are not homogeneous

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#289]
See for instace the Clearò one:

![image](https://cloud.githubusercontent.com/assets/16834220/13991219/8ffe5310-f117-11e5-997b-51fb0f3b1542.png)

Spaces between sections, bolds for titles, lower/upper case...

**Comment by xeviscc** [comment]
Most of the text is "rich text" comming directly from the server side. It is setted in the publication flow. Will have a look for non rich text in order to put correct font weights and sizes.

**Comment by xeviscc** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/10829055/14013016/0e60f9a0-f1aa-11e5-8f82-9a2a9b4477b6.png)
