### ISSUE TITLE
Endpoint /api/application/{idApp}/{processId}/file/{idFile} [DELETE] [Required for UI screen **Publish Service**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#29]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to delete a file from a specific application. **NOTE:** If the type of the file is 'tosca' will return an error. A 'tosca' file cannot be deleted, only updated. |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application/{idApp}/{processId}/file/{idFile} |
| **Call Type:** | DELETE |

**Comment by xeviscc** [comment]
A param in the URL will be needed in order to keep track of the procces.
The param will be a QueryParam/RequestParam called "processInstanceId".

**Comment by pdaniel** [comment]
Endpoint created, please check in using your UI and then pass the task to guido.
