### ISSUE TITLE
It is not clear what the "SIZE" of a service is

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#290]
From an outsider point of view, it is not clear what "SIZE" means. It should be self-explicative like "Size of your entity" or similar. Moreover, there should be a link to somewhere where it is explained what the size is, what is used for and how you can determine the size of your entity.

Finally, all the available sizes should be displayed, not just one.

**Comment by xeviscc** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/10829055/14013016/0e60f9a0-f1aa-11e5-8f82-9a2a9b4477b6.png)
