### ISSUE TITLE
Is the Captcha in all languages?

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#292]
The captcha appears in Spanish even though the Service Catalogue language is English. Does it depend on the IP or it is always in Spanish? If it is the second one, it would be better to have it in English.

![captcha](https://cloud.githubusercontent.com/assets/16834188/13991745/926d942e-f119-11e5-86ba-a08ef797b952.jpg)

**Comment by xeviscc** [comment]
I guess it is shown the language you have configured the browser. We will try to make it match with the language from the selected by the user at the moment in the platform.

**Comment by xeviscc** [comment]
The cpatcha language cannot be changed dynamically due to problems on the way it works.
https://github.com/VividCortex/angular-recaptcha/issues/66
