### ISSUE TITLE
Confirmation email not clear enough

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#295]
The confirmation email is:

"_Dear bonet,
Activation URL: http://lab1.cloudopting.org:8080/#/activate?key=29585370703588572136
Best regards,
CloudOpting team._"

It is not clear if I have to click the URL or not and it lacks personality. The message should say something like this:

Hi "User Name",

Thanks for joining CloudOpting!

Please, click the following link to verify your email: http://lab1.cloudopting.org:8080/#/activate?key=29585370703588572136.

Best regards,

**Comment by guidospadotto-profesia** [comment]
Fixed in f020791
