### ISSUE TITLE
The confirmation link directs to a Tomcat page

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#296]
When you click the activation URL you are directed to a Tomcat page saying:

"If you're seeing this, you've successfully installed Tomcat. Congratulations!"

It is confusing. It should direct you to the main page of the Service Catalogue or a CloudOpting page with a message saying something like: "Thank you! Your email has been successfully verified.".

![activation url](https://cloud.githubusercontent.com/assets/16834188/13992759/9f731d3e-f11d-11e5-8cd3-ba501de176d3.jpg)

**Comment by guidospadotto-profesia** [comment]
Should have been fixed by c5e99eb but I am not able to test because I do not get the e-mail.
Please test again.

**Comment by xeviscc** [comment]
It will be ready in the next release or in development.

**Comment by xeviscc** [comment]
Tested it and it works in prod.
