### ISSUE TITLE
Message unclear when your registration attempt fails

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#297]
When you register with an email already registered but with a different user name the message you get is: "Registration failed! Please try again later."

This message is confusing. It seems like there is a problem with the Service Catalogue and it is impossible to register right now. The message should specify why it is not possible to register the user:

"Registration failed! There has been a technical problem, please try again later."
"Registration failed! This e-mail has already been used, please try another one."
"Registration failed! This User Name has already been used, please try another one."

**Comment by xeviscc** [comment]
Fixed in commit c4e3ac5
