### ISSUE TITLE
Unable to sign in or to recover a password after creating a user 

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#298]
I have created a new user, I have received the confirmation email and have clicked the link.

- When I click "sign in" an enter my details the following message appears:
"Authentication failed! Please check your credentials and try again."
- When I click "Forgot password?" and enter my email, it says the following message:
"E-Mail address isn't registered! Please check and try again."
- When I try to create a user using the same email, says the following message:
"Registration failed! Please try again later."

It looks like if the user has not been created but the email has been saved in the database.

**Comment by guidospadotto-profesia** [comment]
I have checked the status of the DB in the Prod environment. 
There are three records for Miquel Bonet but none is activated, so something must have gone wrong during activation.

**Comment by MiquelBonetSDG** [comment]
I registered using three different emails. Each time, I received the activation email but when I tried to sign in it didn't recognise my credentials.

**Comment by xeviscc** [comment]
Tested in prodaction and it works properly.
