### ISSUE TITLE
Endpoint /application/{idApp}/{processId} [PUT] [Required for UI screen **Publish Service**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#30]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to update the information associated to an application |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application/{idApp} |
| **Call Type:** | PUT |
| **Data Type:** | application/json |
| **Parameters:** | Check schema |

Schema:
```json
{
  "status" : ["Draft", "Ready to publish", "Published"],
  "inputparameters" :
  [
    {
      "type" : "String/Array",
      "enum" : "[value1, value2, ...]",
      "name" : "String",
      "value" : "String"
     },
     {}
  ]
}
```

**NOTE:** If type from inputparameters is an array, it will have a "enum" parameter with an array of possible optinons.

**Comment by xeviscc** [comment]
A param in the URL will be needed in order to keep track of the procces.
The param will be a QueryParam/RequestParam called "processInstanceId".

**Comment by pdaniel** [comment]
Endpoint created please check the endpoint and then pass the task to guido

/application/{idApp}

ApplicationRespurce#updateApplication

**Comment by xeviscc** [comment]
* **TODO:** The processID recived should be sent to the BPMN engine, to let it keep track of the flow.

**Comment by pdaniel** [comment]
I see some code that is not mine in the method. I don;t know if i have to delete it or not. It seems that the process id is set in that code.

**Comment by xeviscc** [comment]
Guido, is this endpoint working? is the BPMN engine reciving th processID?

**Comment by guidospadotto-profesia** [comment]
Hi, I have refactored the method so that it passes the ProcessInstanceId through to the correct method.
