### ISSUE TITLE
Template for Service Description

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#300]
When publishing a service, in the step 1) "Set Global Properties", the gaps to fill should be as follows. Notice the formatting, spaces, etc. proposed. All text JUSTIFIED by default:

[Write the description of the service here]

**FEATURES**
- [Write the features of the service here]
- [Write the features of the service here]
- [Write the features of the service here]

**BENEFITS**
- [Write the benefits of the service here]
- [Write the benefits of the service here]
- [Write the benefits of the service here]

**SUPPORT**
- [Write the support conditions of the service here]

**PRICE**
- Size of the Entity: [Filled automatically from the Size field of the "Set Global Properties" form (ie Small, Medium, Large, Extra-Large)]
- Service: [Filled automatically from the Service Price field of the "Set Global Properties" form (ie 12.345 €)]
- Cloud Hosting: [Filled automatically from the Cloud Hosting Price field of the "Set Global Properties" form (ie (12.345 €)]

**CONTACT**
- [Write your name here]
- [Write your phone number here]
- [Write your e-mail here]

**Comment by xeviscc** [comment]
Take into account that the SERVICE PRICE, the PLAFTORM PRICE and the SERVER SIZE REQUIRED comes from other fields.
![image](https://cloud.githubusercontent.com/assets/10829055/14017757/05662c38-f1ca-11e5-9082-59222c636eab.png)

It cannot be done that way. We can try to set the PRICE in the last position when it is showed in the detail.

**Comment by genismauri** [comment]
_"It cannot be done that way. We can try to set the PRICE in the last position when it is showed in the detail"_ @xeviscc could you please clarify this? I don't get it.

When referring to _"Size of the Entity: [Filled automatically from the Size field of the "Set Global Properties" form (ie Small, Medium, Large, Extra-Large)]"_ I mean to take the number from the gap required above. Are we talking about the same thing?

**Comment by xeviscc** [comment]
Yes.

The think is that the template has all the information as "free text" and the prices comes separately from other fields.
We cannot take the "free text" and parse it modify it with the custom parameters and show it. 
So the better approach is to put the template "free text" in the first place and the PRICE section after that.

**Comment by genismauri** [comment]
I see we have to 2 options:

**1) Add all the free-text fields first + then the automatic Pricing**

[Write the description of the service here]

**FEATURES**
- [Write the features of the service here]
- [Write the features of the service here]
- [Write the features of the service here]

**BENEFITS**
- [Write the benefits of the service here]
- [Write the benefits of the service here]
- [Write the benefits of the service here]

**SUPPORT**
- [Write the support conditions of the service here]

**CONTACT**
[Write your name here]
[Write your phone number here]
[Write your e-mail here]

**PRICE**
- Size of the Entity: [Filled automatically from the Size field of the "Set Global Properties" form (ie Small, Medium, Large, Extra-Large)]
- Service: [Filled automatically from the Service Price field of the "Set Global Properties" form (ie 12.345 €)]
- Cloud Hosting: [Filled automatically from the Cloud Hosting Price field of the "Set Global Properties" form (ie (12.345 €)]

**2) Create required gaps (like the ones you did with the pricing) for all sections, so the service file would be created automatically based on the introduced info > that would be suitable**

**Comment by xeviscc** [comment]
To do that a huge modification on the platform has to be done.

**Comment by genismauri** [comment]
OK, it's something.
We will check it again in the next release ;)

**Comment by xeviscc** [comment]
Does the following screenshot work for you?
![image](https://cloud.githubusercontent.com/assets/10829055/14102754/c96441f8-f59c-11e5-84c5-96e557383555.png)

**Comment by genismauri** [comment]
A couple of things:
- As suggested in the template, no need to add "name and surname" either "e-mail" in the CONTACT.
- There's an extra space between PRICE title and the Size row.
- Also FEATURES and BENEFITS are missing in this case.

**Comment by xeviscc** [comment]
1. The inclusion or not of the name and e-mail is responsibility of the publisher, as it is FREE TEXT.
2. True, will fix it.
3. As in the point 1. The inclusion or not of the FEATURES and BENEFITS is the publisher's responsibility as it is FREE TEXT.

**Comment by genismauri** [comment]
_The inclusion or not of the name and e-mail is responsibility of the publisher, as it is FREE TEXT_ > Sure, but I was pointing out not to include the tags "name" and "email" in the Contact section.

See this for instance, tags are not necessary:
![image](https://cloud.githubusercontent.com/assets/16834220/14104406/59d17460-f5a5-11e5-9471-3a74dd24d1d2.png)

**Comment by xeviscc** [comment]
I understand, but as I said before, even the part that states _**Name, Surname:**_ and _**E-mail:**_ are free text, not depending on the platform, so the publishers could choose to add it or to delete it.

**Comment by xeviscc** [comment]
@genismauri Could you check te resolution and close the issue if it is solved.

**Comment by genismauri** [comment]
Is this free text? (belongs to Clearò) Or with the implemented changes for CONTACT and PRICE sections should have been fixed?

![image](https://cloud.githubusercontent.com/assets/16834220/14138430/887a000c-f66d-11e5-973e-4f2388e1051c.png)

**Comment by xeviscc** [comment]
Here I attach a screenshot:
![image](https://cloud.githubusercontent.com/assets/10829055/14138515/eb1122f4-f66d-11e5-89bb-4305452cbd8c.png)

Here you can see the **Service Price/Platform Price/Size** specific inputs. From that info we create the PRICE section at the end.
The others comes from the **Service Description**. As you can see there is a template inside the text box in order to give the user some hints in how he can organize the text.

The user could duplicate each part, the user could dubplicate the PRICE, the user could write not formated text, the user could create a bran new section, the user could write anything as it is **FREE TEXT**

**Comment by genismauri** [comment]
Looks good now, thanks!
