### ISSUE TITLE
Translate to ROMANIAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#301]
All files has to be translated to ROMANIAN.
Check files at: https://github.com/CloudOpting/cloudopting-manager/tree/master/rest-component/src/main/webapp/i18n/ro

**Comment by ciprianpavel** [comment]
Duplicate of #241. There are some strings remaining that will be translated as part of this issue.

**Comment by xeviscc** [comment]
This is why I closed the #241. This is a subtask and from now on all updates has to be posted here.

**Comment by xeviscc** [comment]
New string to translate at publish.json.
Check "description.template".
