### ISSUE TITLE
Translate to ITALIAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#302]
All files has to be translated to ITALIAN.
Check files at: https://github.com/CloudOpting/cloudopting-manager/tree/master/rest-component/src/main/webapp/i18n/it

**Comment by xeviscc** [comment]
New string to translate at publish.json.
Check "description.template".

**Comment by ClaudioSola** [comment]
All files has to be translated to ITALIAN
