### ISSUE TITLE
Translate to CATALAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#305]
All files has to be translated to CATALAN.
Check files at: https://github.com/CloudOpting/cloudopting-manager/tree/master/rest-component/src/main/webapp/i18n/ca

**Comment by xeviscc** [comment]
Missing part of terms.json to be translated:
https://github.com/CloudOpting/cloudopting-manager/commit/f9e1f7c87eb31606b853e43fa4e7011b59ce589f?diff=unified

**Comment by xeviscc** [comment]
menu.json has to be fixed. 
_the title should be Menú, not Mení_

**Comment by genismauri** [comment]
Already fixed.

**Comment by xeviscc** [comment]
There are missing sentences to be translated:

![image](https://cloud.githubusercontent.com/assets/10829055/14201718/f849764c-f7f3-11e5-98e3-5b02146487dd.png)

**Comment by xeviscc** [comment]
New string to translate at publish.json.
Check "description.template".

**Comment by genismauri** [comment]
@xeviscc Everything missing was translated 2 days ago.
I'm afraid it was just at the time you did the last release.

https://github.com/CloudOpting/cloudopting-manager/blob/master/rest-component/src/main/webapp/i18n/ca/terms.json

**Comment by xeviscc** [comment]
@genismauri I am affraid you are wrong. I check this things in development. I do have the most updated version of the platform.

Just checked the file you posted, and here you can see an screenshot.
![image](https://cloud.githubusercontent.com/assets/10829055/14202148/b08a48e2-f7f6-11e5-8307-c8cfed5fd393.png)

**Comment by genismauri** [comment]
My apologies, you were right.
I believe it's all translated now.
