### ISSUE TITLE
Translate to FRENCH

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#307]
All files has to be translated to FRENCH.
Check files at: https://github.com/CloudOpting/cloudopting-manager/tree/master/rest-component/src/main/webapp/i18n/fr

@jmcerpa is assigned because Carlos Rubia does not have an account or it is not in the project.

**Comment by XavierBlanch** [comment]
French Translation:

I have  translated to french  the files until  "contact.json" included

**Comment by xeviscc** [comment]
Partial translations in attached file: 


[CloudOpting_FR.zip](https://github.com/CloudOpting/cloudopting-manager/files/199220/CloudOpting_FR.zip)

**Comment by xeviscc** [comment]
New string to translate at publish.json.
Check "description.template".

**Comment by xeviscc** [comment]
Nathalie Coue states that she translated all the sentences to FRENCH. Find it in email from friday 2016/04/01.
Only needs to be integrated.

**Comment by xeviscc** [comment]
Attached translation from the email.
[CloudOpting_FR_01-04-2016.zip](https://github.com/CloudOpting/cloudopting-manager/files/295690/CloudOpting_FR_01-04-2016.zip)
