### ISSUE TITLE
Endpoint /api/application/{idApp}/{processId} [DELETE] [Required for UI screen **"Service List - Manager"**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#31]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to request a deletion, a decommission. |
| **Screen that needs the endpoint:** |  Taylor Service |
| **Endpoint required:** |  /api/application/{idApp}/{processId} |
| **Call Type:** | DELETE |

**Comment by xeviscc** [comment]
A param in the URL will be needed in order to keep track of the procces.
The param will be a QueryParam/RequestParam called "processInstanceId".

**Comment by pdaniel** [comment]
Endpoinit created. Please check it and then pass to Guido

/application/{idApp}/{processId}

ApplicationResource#deleteApplication

**Comment by xeviscc** [comment]
Call done and working from "Service List - Manager" screen.

**Comment by guidospadotto-profesia** [comment]
I am closing this with commit 5c61ce0 .
There is still the issue with not being possible to clean-up JackRabbit nodes associated to the Application, but that is the subject of #41
