### ISSUE TITLE
Add button to "upload needed files" screen

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#310]
Add a new button like 'SKIP' or 'SKIP &NEXT' for every page as the user does not want to change something on that page. As an example the 'Upload needed files' page could use it.

**Comment by xeviscc** [comment]
Solved.
![image](https://cloud.githubusercontent.com/assets/10829055/15679199/446415a0-2751-11e6-89dd-058209e0c88b.png)
