### ISSUE TITLE
Activiti js object is undefined when updating a service

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#314]
When I click on the "Edit" button in the Service List entry for an existing service I am shown the first page of the publish process.
I do change something to see if it works, then I click on "Update" (Save is disabled).
Nothing happens.
It seems that, on line 129 of publish.service.js, the "activiti" variable is not found, so line 138
of the same file fails. 
The resolution of #221 depends on this.

**Comment by xeviscc** [comment]
The "activiti" variable is empty or null because it is created when a new process is created.

Do we have a way to get a process ID before starting updating? This was one of the main problems when a new Activiti BPMN flow was asked in order to be able to update a service.

**Comment by xeviscc** [comment]
Posponed to the next release.

**Comment by xeviscc** [comment]
Closing. Alternative methods provided for updating services.
