### ISSUE TITLE
Colours of the images in the home page header/banner are not updated to the current palette

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#316]
Don't know who is the responsible for this, but those greens are outdated.
The current look and feel doesn't match with this banner.

**Comment by xeviscc** [comment]
Designers from Worldline did it in the first place. I do not know if someone want to participate, if not I will ask them to adapt it.

In the other hand, we need the texts on images translated in order to ask the designers build an image for each language.

**Comment by xeviscc** [comment]
Could you explain what do you mean exactly when you say "current palette"?

**Comment by genismauri** [comment]
old greens vs new blues.

**Comment by xeviscc** [comment]
Images translated already have the new "palette"

**Comment by xeviscc** [comment]
Images are now following the "new colors"
