### ISSUE TITLE
Translate images to SPANISH

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#318]
Translate text into images.

**Comment by jmcerpa** [comment]
#####First:
--empty--
#####Second:
- Publicar: Cumpliendo los requisitos de CloudOpting, una aplicación puede ser publicada en el catálogo de servicios.
- CloudOpting catálogo de servicios
- Suscripción: Después de un sencillo método de compra, una entidad puede suscribirse a cualquiera de los servicios ofrecidos en el catálogo.

#####Third:
- **light green ball:**
Mejor control de recursos y monitorización de aplicaciones.
- **dark green ball:**
Promoción más amplia a nivel europeo gracias a una amplia red de distribución.
- **turquoise ball:**
Nuevas oportunidades de negocio para las PYME gracias a disponer de datos abiertos para ser reutilizados.
- **Light blue ball:**
Reducción del coste total gracias a tener un gran número de usuarios, por lo que se reduce el coste unitario.
- **yellow ball:**
Automatización del despliegue de aplicaciones mediante Docker commander y sus componentes.
- **red ball:**
Acceso a un amplio catálogo de aplicaciones listas para ser usadas.

**Comment by xeviscc** [comment]
First slide updated, please provide translation.
Texts on sliders. Find it attached. (In the first slide, some text may be added on the "empty" white part.
**slide 1**
![image](https://cloud.githubusercontent.com/assets/10829055/14427415/f07233a6-fff4-11e5-9f64-957d8de40019.png)
**slide 2**
![img_slide2](https://cloud.githubusercontent.com/assets/10829055/14308791/b82c436c-fbd8-11e5-9d1d-1ba2343bf3f1.png)
**slide 3**
![img_slide3](https://cloud.githubusercontent.com/assets/10829055/14308795/bfe7917e-fbd8-11e5-8688-ae59d1a3ec57.png)

**Comment by jmcerpa** [comment]
**slide 1:**
Qué es CloudOpting?
CloudOpting es un marketplace Europeo donde las Administraciones Públicas pueden encontrar los servicios TIC más adecuados a sus necesidades de negocio.
