### ISSUE TITLE
Translate images to CATALAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#319]
Translate text into images.

**Comment by genismauri** [comment]
Could you please indicate exactly the text to translate?

**Comment by xeviscc** [comment]
Texts on sliders. Find it attached. (In the first slide, some text may be added on the "empty" white part.
**slide 1**
![img_slide1](https://cloud.githubusercontent.com/assets/10829055/14308790/b5a97c2c-fbd8-11e5-8dcc-506ee12eb345.png)
**slide 2**
![img_slide2](https://cloud.githubusercontent.com/assets/10829055/14308791/b82c436c-fbd8-11e5-9d1d-1ba2343bf3f1.png)
**slide 3**
![img_slide3](https://cloud.githubusercontent.com/assets/10829055/14308795/bfe7917e-fbd8-11e5-8688-ae59d1a3ec57.png)

**Comment by genismauri** [comment]
Slide 2:
- **Publica** Omplint els requeriments tècnics de CloudOpting, la vostra aplicació pot ser publicada al Catàleg de Serveis.
- **Subscriu-te** Després de seguir un senzill procés d'adquisició, la vostra organització es pot subscriure a qualsevol dels serveis oferits al Catàleg de Serveis.

Slide 3:
- Millor control dels recursos i monitorització de les aplicacions.
- Promoció a nivell europeu gràcies a disposar d'una àmplia i potent xarxa de distribució.
- Automatització del desplegament de les aplicacions mitjançant l'orquestrador de Docker i els seus components.
- Noves oportunitats per les PIME gràcies a poder disposar de dades obertes per a ser reutilitzades.
- Reducció del Cost Total de Propietat atès el gran volum d'usuaris i, en conseqüència, de tenir un baix preu unitari.
- Accés a un ampli catàleg d'aplicacions personalitzades i llestes de ser utilitzades.

**Comment by genismauri** [comment]
First slide I guess it should be removed > it provides no info, it's a total filler.

**Comment by xeviscc** [comment]
Updated the first screen. Please, provide translation.

**Comment by genismauri** [comment]
Slide 1:
CloudOpting és un marketplace en el qual les Administracions Públiques poden trobar els serveis TIC més adequats per cobrir les seves necessitats de negoci.
