### ISSUE TITLE
Endpoint /api/customization [POST] [Required for UI screen **Taylor Service**]

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#32]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to create a new instance of a given application |
| **Screen that needs the endpoint:** |  Taylor Service |
| **Endpoint required:** |  /api/customization |
| **Call Type:** | POST |
| **Request Data Type:** | application/json |
| **Request Parameters:** | Check schema |

Schema:
```json
{
  "idApp" : "String",
  "user" : "String",
  "organization" : "String",
  "type" : ["Test", "Production"]
}
```

**Comment by pdaniel** [comment]
Done, please test it

CustomizationResource#create
