### ISSUE TITLE
Translate images to ROMANIAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#320]
Translate text into images.

**Comment by xeviscc** [comment]
Any news on that?

**Comment by xeviscc** [comment]
Texts on sliders. Find it attached. (In the first slide, some text may be added on the "empty" white part.
**slide 1**
![image](https://cloud.githubusercontent.com/assets/10829055/14427415/f07233a6-fff4-11e5-9f64-957d8de40019.png)
**slide 2**
![img_slide2](https://cloud.githubusercontent.com/assets/10829055/14308791/b82c436c-fbd8-11e5-9d1d-1ba2343bf3f1.png)
**slide 3**
![img_slide3](https://cloud.githubusercontent.com/assets/10829055/14308795/bfe7917e-fbd8-11e5-8688-ae59d1a3ec57.png)

**Comment by ciprianpavel** [comment]
Slide 1 (please proof read it in English also):
"CloudOpting este o piață europeană unde administrațiile publice pot găsi serviciile TIC cele mai potrivite pentru a-și acoperi nevoile de afaceri."

**Comment by ciprianpavel** [comment]
Slide 2 (please proof read it in English also):
"Publicare:Îndeplinind cerințele CloudOpting, o aplicație poate fi publicată în Catalogul de Servicii"
"Subscriere:După o metodă simpla de achiziție, o Entitate poate Subscrie la orice Serviciu din cadrul Catalogului"
"CloudOpting"
"Catalogul de Servicii"

**Comment by ciprianpavel** [comment]
Slide 3 (from left to right):
"Control mai bun al resurselor și monitorizarea aplicației din punct de vedere afacere"
"Noi oportunități de afacere pentru IMM prin accesul la date deschise"
"Promovare pe scară largă la nivel European mulțumită unui rețele puternice"
"Reducerea Costului Total grație unei populații mai mare de utilizatori, deci cost unitar scăzut"
"Access la un catalog de aplicații personalizate gata de utilizare"
"Automatizarea lansării aplicațiilor utilizând componente Docker"
