### ISSUE TITLE
Translate images to ITALIAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#321]
Translate text into images.

**Comment by xeviscc** [comment]
Any news on that?

**Comment by ClaudioSola** [comment]
Hi,
In the early afternoon, the translation will be available.

**Comment by xeviscc** [comment]
Texts on sliders. Find it attached. (In the first slide, some text may be added on the "empty" white part.
**slide 1**
![image](https://cloud.githubusercontent.com/assets/10829055/14427415/f07233a6-fff4-11e5-9f64-957d8de40019.png)
**slide 2**
![img_slide2](https://cloud.githubusercontent.com/assets/10829055/14308791/b82c436c-fbd8-11e5-9d1d-1ba2343bf3f1.png)
**slide 3**
![img_slide3](https://cloud.githubusercontent.com/assets/10829055/14308795/bfe7917e-fbd8-11e5-8688-ae59d1a3ec57.png)

**Comment by ClaudioSola** [comment]
Slide 1
Eng --> Cloud Opting is an European marketplace where Public Administrations can find the most suitable ICT services to cover its bussiness needs.
Ita --> Cloud Opting è un mercato europeo dove le Pubbliche Amministrazioni possono trovare i servizi ICT più adatti per ricoprire le proprie esigenze di business.

Slide 2
Eng --> Publish Fulfilling the Cloud Opting requirements, an application can be published into the Services Catalogue.
Ita --> Pubblicare Soddisfare i requisiti di Cloud Opting, un'applicazione può essere pubblicata nel Catalogo dei Servizi.

Eng --> Subscribe. After a simple purchasing method, an Entity can Subscrive any of the Services offered within the Catalogue
Ita --> Abbonarsi. Dopo una semplice procedura d'acquisto, un Ente può Abbonarsi ad un qualunque Servizio contenuto all'interno del Catalogo


Slide 3
Eng --> Better control of the resources and business monitoring of the application
Ita --> Un miglior controllo delle risorse e delle attività di monitoraggio dell'applicazione

Eng --> Wilder promotion at European level thanks to a powerful channel network
Ita --> Ampia promozione a livello europeo grazie ad una possente rete.

Eng --> Automation of deployment of application by means of the Docker commander and components
Ita --> Automazione della distribuzione delle applicazioni attraverso il Docker commander ed i suoi componenti.

Eng --> Reduction of the Total Cost of Ownership thanks to having lot of users thus less unitary cost
Ita --> Riduzione del Costo Totale di Possesso grazie al fatto di avere molti utenti e quindi un basso costo unitario.

Eng --> New business opportunities for the SME by having open data to be reused
Ita --> Nuove opportunità di business per le PMI di disporre di open data riutilizzabili

Eng --> Access to a wide catalogue of ready-to-use customized application
Ita --> L'accesso ad un ampio catalogo di applicazioni pronte all'uso e personalizzabili
