### ISSUE TITLE
Implement the jclouds module to support Digital Ocean's

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#329]
The module of jclouds has to have compatibility to support automatic deployment in Digital Ocean's clouds.

**Comment by ciprianpavel** [comment]
The original requirements were for Azure and CloudStack.
@xeviscc  Please provide access to a development environment for VMWare in order to start investigating this issue.

**Comment by xeviscc** [comment]
Check http://mvnrepository.com/artifact/org.apache.jclouds.labs/digitalocean2/1.9.2

**Comment by xeviscc** [comment]
Waiting for IMI to provide the environment.

**Comment by gcabezas** [comment]
The digitaloceans tokens were sent on the 1st July 12:20 CEST

**Comment by xeviscc** [comment]
@cpopsa Could you please test your code with the credentials provided.

**Comment by cpopsa** [comment]
Done
