### ISSUE TITLE
Endpoint /api/customization/{idCustom} [DELETE] [Required for UI screen **Manage Subscription / List of instances**] 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#33]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint used as a decomission action for the given instance. |
| **Screen that needs the endpoint:** |  Manage Subscription / List of instances |
| **Endpoint required:** |  /api/customization/{idCustom} |
| **Call Type:** | DELETE |

**Comment by pdaniel** [comment]
Done, please test
