### ISSUE TITLE
Create a drawing for ilustrate the BMPN processes

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#337]
Create a drawing for ilustrate the BMPN processes

**Comment by ildave** [comment]
I have made two screenshots of the process as shown in the Activity Editor in Eclipse.
![publishprocess](https://cloud.githubusercontent.com/assets/3855605/15668310/e52b41ac-271a-11e6-98e6-892fbb9f5658.png)
![updateprocess](https://cloud.githubusercontent.com/assets/3855605/15668311/e55205e4-271a-11e6-9d1c-0a406496f399.png)

**Comment by xeviscc** [comment]
Thank you. All others remain the same?

**Comment by ildave** [comment]
Just to be sure, here they are:

<img width="496" alt="servicedelete" src="https://cloud.githubusercontent.com/assets/3855605/15671484/56c0d5e2-272b-11e6-81db-c8de5cc317d4.png">
![orchestration](https://cloud.githubusercontent.com/assets/3855605/15671485/56ee37da-272b-11e6-9b51-e92638ae6c06.png)

**Comment by xeviscc** [comment]
@ildave Can we have one for the subscription?

**Comment by guidospadotto-profesia** [comment]
There is no BPM process for subscription, if I remember correctly.

**Comment by xeviscc** [comment]
Deliverable 2.4 done.
