### ISSUE TITLE
Create a drawing for ilustrate the docker crane components/behaviour

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#339]
Create a drawing for ilustrate the docker crane components/behaviour

**Comment by crubia** [comment]
Look this picture and tell me if need something else.

[Docker Crane Drawing.pdf](https://github.com/CloudOpting/cloudopting-manager/files/277314/Docker.Crane.Drawing.pdf)

**Comment by xeviscc** [comment]
Thank you.

**Comment by xeviscc** [comment]
Deliverable 2.4 done.
