### ISSUE TITLE
Endpoint /api/customization/{idCustom} [PUT] [Required for UI screen **List of instances**]

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#34]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to update the information associated to a customization |
| **Screen that needs the endpoint:** |  List of instances |
| **Endpoint required:** |  /api/customization/{idCustom} |
| **Call Type:** | PUT |
| **Data Type:** | application/json |
| **Parameters:** | Check schema |

Schema:
```json
{
  "status" : ["Stopped", "Deploied"]
}
```

**NOTE:** The change of the status will trigger the process to do what the stuts states.

**Comment by pdaniel** [comment]
Done, please test 

CustomizationResource#update
