### ISSUE TITLE
Create a drawing for ilustrate the Jackrabbit filesystem management

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#340]
Create a drawing for ilustrate the Jackrabbit filesystem management

**Comment by ildave** [comment]
What do you need to see in the drawing? The structure of the Jackrabbit folders in the filesystem?

**Comment by xeviscc** [comment]
The structure that was decided to use in order to keep all files ordered by organization/service for example.

**Comment by guidospadotto-profesia** [comment]
The JackRabbit path for resources is built with this logic:
organizationKey + "/" + applicationToscaName + "/template"
all resources are saved there.

**Comment by xeviscc** [comment]
So, are all files saved in the same path? There is no distinction between tosca zip file, media files, library files, etec.. ?

**Comment by guidospadotto-profesia** [comment]
All files are saved in the same path, yes. The only distinction is in the file name. The "meaning" of a file depends on in which attribute of the "Application" entity its complete path is saved into. In other words, if "/A/B/C.png" is saved in the "appLogo" attribute, then it's the logo.

**Comment by xeviscc** [comment]
Can we have some kind of drawing to illustrate the text?

**Comment by gioppoluca** [comment]
Yes we are using JR just as a BIN for storing all the stuff of the application the real master for the info is the DB that knows what a file means thanks to the fact that is saved the path on a column or the other.
What we need the diagram for?

**Comment by xeviscc** [comment]
We have to illustrate some deliverables for resubmission, and we wanted to have some pretty drawings.

**Comment by xeviscc** [comment]
Deliverable 2.4 done.
