### ISSUE TITLE
Cannot replace the current TOSCA file for Sentilo in the service manager.

### ISSUE THREAD

**Issue by gcabezas** [CloudOpting/cloudopting-manager#341]
Cannot replace the current TOSCA file for Sentilo in the service manager.
It gets stucked in the "Upload needed files" tab.

**Comment by xeviscc** [comment]
Are you trying to edit an existing service!?

**Comment by gcabezas** [comment]
yes, trying to update the Sentilo TOSCA file.

**Comment by xeviscc** [comment]
Issue already opened to solve service edit. Check https://github.com/CloudOpting/cloudopting-manager/issues/73
