### ISSUE TITLE
Monitoring system access as administrator

### ISSUE THREAD

**Issue by crubia** [CloudOpting/cloudopting-manager#343]
if I login as administrator and try to see the monitoring system through the DASHBOARD Label, the UI shows a prohibited signal and don't let me go ahead.

**Comment by xeviscc** [comment]
The dashboard for an administrator should be different from others. We will have to think about what to show in the administrator dashboard.

**Comment by gioppoluca** [comment]
At the moment the <administrator should just not have the filters.
What we need to check is that the provider just see its own stuff and can work.
Before the review we had to set all to admin since there was the problem on the correct accesses to function calls
