### ISSUE TITLE
Graphs in the monitoring system

### ISSUE THREAD

**Issue by crubia** [CloudOpting/cloudopting-manager#344]
There are several graphs coming from Zabbix that cannot be consulted (data cannot be loaded). Moreover I cannot select different periods of time to see in the graph, the button Apply doesn't work.

On the other hand I cannot find the graphs form elasticsearch (KIbana).

**Comment by xeviscc** [comment]
This is more than one issue.
1. Some of the data that can be selected shows nothing.
2. The data picker does not work.
3. Elasticsearch graphs are not in the monitoring screen.
@gioppoluca Could you take care of this issue?
