### ISSUE TITLE
After changing the password an email is not received

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#346]
If you change the password of your account, an email should be received to warn you and to confirm that it has been changed correctly.

**Comment by ildave** [comment]
Which is the endpoint called when an user change his password?

**Comment by xeviscc** [comment]
The endpoint is: api/account/change_password

**Comment by ildave** [comment]
I have pushed a change for this, commit 40def5d25ea2d1bfe884b1f015e410ad1e61f179
