### ISSUE TITLE
Links broken for "Terms and Conditions" and "Privacy Policy"

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#347]
From the "Privacy Policy" page, the link to "Terms_and_Conditions" is broken.
Same happens the other way around.

![sc016_general_terms_and condition_of_use](https://cloud.githubusercontent.com/assets/16834220/15676671/7216d8de-2747-11e6-955f-5bbb3d81d142.JPG)

**Comment by xeviscc** [comment]
Already solved. Duplicated of https://github.com/CloudOpting/cloudopting-manager/issues/342
