### ISSUE TITLE
Pull-down menu is broken

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#348]
For a normal user (not admin).
When you click, it shows empty options.

![sc001_menu empty](https://cloud.githubusercontent.com/assets/16834220/15677954/b78f3064-274c-11e6-8915-4fd898b8af76.JPG)

**Comment by xeviscc** [comment]
Fixed. ![image](https://cloud.githubusercontent.com/assets/10829055/15679608/cb533a86-2752-11e6-9921-1c6500d6d6eb.png)
