### ISSUE TITLE
Change endpoint /api/application/list [GET] for /api/application [GET] [Required for UI screen **Service Catalog**]

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#35]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to get all applications |
| **Screen that needs the endpoint:** |  Service Catalog |
| **Endpoint required:** |  /api/application |
| **Call Type:** | GET |
| **Response Data Type:** | application/json |
| **Query Parameters:** | page(Integer), size(Integer), sortBy("field name"), sortOrder(["asc", "desc"]), filter(String) |

**Comment by pdaniel** [comment]
The endpoint is done. Please check.

**Comment by xeviscc** [comment]
The endpoint that has to be changed was /api/application/list not /api/application/listunpaginaded.
I fixed it myself!
