### ISSUE TITLE
Account Reset - "Forgot password" doesn't work

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#354]
Button "Send" after entering the mail address does nothing.

**Comment by xeviscc** [comment]
Cannot reproduce in a development environment:

**If the user exists:**

![image](https://cloud.githubusercontent.com/assets/10829055/16652476/3141c604-444b-11e6-8907-abc3d6d7e5ad.png)

**And the mail:**

![image](https://cloud.githubusercontent.com/assets/10829055/16652468/23fc6166-444b-11e6-99fc-91eaf53d94f8.png)

**If the user does not exists:**

![image](https://cloud.githubusercontent.com/assets/10829055/16652489/41c5e474-444b-11e6-83e5-6bfd5d4503ce.png)
