### ISSUE TITLE
Create a drawing for ilustrate the Subscription

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#357]
Create a drawing for ilustrate the Subscription

**Comment by guidospadotto-profesia** [comment]
Where is "the Subscription process" defined?

**Comment by xeviscc** [comment]
Go to catalog -> select a service to subscribe -> customize service -> choose cloud environment -> finish

**Comment by guidospadotto-profesia** [comment]
So it might be related to the "customisation" feature. Who did implement it?

**Comment by xeviscc** [comment]
Deliverable 2.4 done.
