### ISSUE TITLE
Change endpoint /api/customization/list [GET] for /api/customization[GET] [Required for UI screen **Instances List Manager**]

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#36]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to get all customizations |
| **Screen that needs the endpoint:** |  Instances List Manager|
| **Endpoint required:** |  /api/customization |
| **Call Type:** | GET |
| **Response Data Type:** | application/json |
| **Query Parameters:** | page(Integer), size(Integer), sortBy("field name"), sortOrder(["asc", "desc"]), filter(String), owner(String) |

**NOTE:** It returns applications, but the filter applies to the instances of the applications, not the applicaiton itself.

**Comment by pdaniel** [comment]
Done please check

**Comment by xeviscc** [comment]
Checked. Done!
