### ISSUE TITLE
Publication Wizard - Be able to skip the second step (Upload needed files)

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#365]
Be able to skip the second step (Upload needed files)

**Comment by xeviscc** [comment]
@ildave Does activity have to do something in order to be able to skip uploading files between the metadata and the TOSCA Archive?

**Comment by ildave** [comment]
I think that to be able to skip the publishing process must be modified to allow the process to go on with a missing piece of data. As far as I know @gioppoluca designed this process, so he can confirm if this is correct.

**Comment by xeviscc** [comment]
@ildave @gioppoluca coordinate in order to solve the issue.

**Comment by xeviscc** [comment]
@ildave Estimate the issue in order to decide which release will have this functionality.

**Comment by xeviscc** [comment]
@ildave @guidospadotto-profesia We need an estimation of this issue.

**Comment by xeviscc** [comment]
Check it carefully because I think we use to skip this step before it was mandatory.

**Comment by xeviscc** [comment]
@ildave It is done in the UI check if it breaks the BPMN.

**Comment by ildave** [comment]
I have tried to create a new service skipping the second step, and everything went fine: the data has been saved on the database and the log image and the tosca file have been stored on JackRabbit, and there were no errors in the application logs from the process.
