### ISSUE TITLE
TOSCA IDE - Message warning to check the TOSCA

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#368]
Related to #367 .

While the TOSCA IDE is not able to detect errors it should show a message saying something like:

"Don't forget to check the TOSCA file generated in case there are some errors."

**Comment by gioppoluca** [comment]
Not useful and not so stylish.
Applications should raise errors or do their job.

**Comment by gioppoluca** [comment]
This warning will have to go on the manual
