### ISSUE TITLE
Endpoint /application/{idApp}/file [GET] [Required for UI screen **Publish Service (on update)**]

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#39]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to get a list of files for a specific application. |
| **Screen that needs the endpoint:** |  Publish Service |
| **Endpoint required:** |  /api/application/{idApp}/file |
| **Call Type:** | GET |

**NOTE:** ``@Guido:`` Is it going to be needed a processId?

**Comment by xeviscc** [comment]
@cpopsa Could you please write down a status of this issue?

**Comment by ciprianpavel** [comment]
Xavi has a question for you on this issue.

**Comment by guidospadotto-profesia** [comment]
@xeviscc  see commit df9f3bc . I could not test because there's no UI trigger.

**Comment by guidospadotto-profesia** [comment]
Implemented and tested in c9d9be4
