### ISSUE TITLE
Crane cannot contect to remote Docker endpoint

### ISSUE THREAD

**Issue by cpopsa** [CloudOpting/cloudopting-manager#392]
Steps:
VM
1. Create a VM in Digital Ocean (IP: 198.199.76.244)
2. Install Docker in VM
3. Enable Docker remote API with TLS disable, at endpoint http://198.199.76.244:2375
4. Start Docker
5. Test Docker endpoint from browser http://198.199.76.244:2375/images/json
![dockerremote](https://cloud.githubusercontent.com/assets/1550827/16655292/515103a8-4462-11e6-89ec-c8c660f9dfc0.png)

Crane
1. Start Crane on local machine with command: docker-compose -f development.yml up
2. Access Crane Swagger UI from browser
3. Call the api POST /cluster/provisionedSingleMachine with parameter endpoint = http://198.199.76.244:2375
4. Result is
{
  "description": "Error while connecting with provided docker host. Endpoint: 'http://198.199.76.244:2375' exception:Cannot connect with docker client at 'https://198.199.76.244:2375'",
  "error": "generic"
}
![craneswaggerui](https://cloud.githubusercontent.com/assets/1550827/16655337/814d22a8-4462-11e6-941b-771981438d5c.png)

I will leave the machine 198.199.76.244 up for testing purposes.

**Comment by jmcerpa** [comment]
Crane uses TLS to communicate with docker host. You can use genCerts.sh script to generate certificates.
On the other hand, when you use development.yml, emulatehost is deployed. This is a container that emulates a docker host for testing. You can use it to test or use it as example to configure your docker host.

**Comment by cpopsa** [comment]
I followed the steps below and it worked:
- generate CA certificates with genCerts.sh script
- copy server certificates by hand to DigitalOcean vm 198.199.76.244
- start Docker remote with TLS enabled
- connect from localhost Crane to remote Docker https://198.199.76.244:2376

Result:
connection worked

So I'v done the certificates operations (generation and copy) by hand. The question is in a prod scenario how the certificates are produced and how they get copied to remote vm's and crane environment? Am I missing some info here?

**Comment by jmcerpa** [comment]
Certificates are copied in VM when the VM is created and provisioned. But Crane isn't who creates the VM.
If you want use Crane standalone, you should create and copy this certificate by hand.

**Comment by crubia** [comment]
Carlos Rubia Marcos
Project Manager
Networks, Systems and Cloud

Product Development
