### ISSUE TITLE
Status color of the "Instances Service" list is random

### ISSUE THREAD

**Issue by gcabezas** [CloudOpting/cloudopting-manager#395]
The green/red color dot of the status column in the Instances Service screen seems to be random. 
It changes from time to time when refreshing the screen.

**Comment by xeviscc** [comment]
The status is given by the customization table and can be "true" or "false". I added some check in order to be more accurate but cannot guarantee it will change the current behaviour.

**Comment by xeviscc** [comment]
@cpopsa Check this issue, the response from the server is different each time.

**Comment by ciprianpavel** [comment]
I have added another check on Zabbix login status. The monitoring info comes from Zabbix not from CO.
