### ISSUE TITLE
When an item from the host is selected, sometimes nothing is shown.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#401]
Seems that sometimes the graph is not created. From the javascript console seems that the data comes correctly, but never shown.

**Comment by xeviscc** [comment]
Seems that the problem is the amount of data. It should be segmented by month in the first place, for example.

**Comment by gioppoluca** [comment]
Graphs now work,
problems could occur in case of big range or bad network connection or in case of getting data for a period that zabbix does not have stored hystory data (zabbix does not keeps hystory long as elastic)
