### ISSUE TITLE
Update versions in the platform if needed.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#405]
Update versions in the platform if needed.

https://github.com/CloudOpting/cloudopting-manager/wiki/Tools-used

**Comment by genismauri** [comment]
Could we have it updated by this Friday 16/09?

**Comment by cpopsa** [comment]
I updated the versions of Spring Boot - JGraphT. Can somebody check Docker - Kibana ?

**Comment by xeviscc** [comment]
Updated docker.
