### ISSUE TITLE
Starting the platform gets stucked after Flyway decides it is not necessary to migrate.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#407]
Starting the platform gets stucked after Flyway decides it is not necessary to migrate.

```console
[INFO] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1.5
[INFO] org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
```

We need to understand what Spring does in order to be able to solve this issue.

**Comment by gioppoluca** [comment]
lined to #408

**Comment by ciprianpavel** [comment]
Can not reproduce on my machine:
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/ (filename: )
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V0.1__DbInit.sql (filename: V0.1__DbInit.sql)
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V1.1__applications_addImageRef.sql (filename: V1.1__applications_addImageRef.sql)
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V1.2__cloudaccounts_addIsTrial.sql (filename: V1.2__cloudaccounts_addIsTrial.sql)
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V1.3__application_media_media_content.sql (filename: V1.3__application_media_media_content.sql)
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V1.4__applications_logo_ref.sql (filename: V1.4__applications_logo_ref.sql)
[DEBUG] org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner - Filtering out resource: db/migration/V1.5__customizations_zabbixAndDeployInfo.sql (filename: V1.5__customizations_zabbixAndDeployInfo.sql)
[INFO] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1.5
[INFO] org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
[DEBUG] eu.cloudopting.config.SecurityConfiguration - Configure http security
[INFO] eu.cloudopting.Application - Running with Spring profile(s) : [dev]
[DEBUG] eu.cloudopting.config.SecurityConfiguration - Configure web security
[DEBUG] eu.cloudopting.config.MailConfiguration - Configuring mail server
log4j:WARN No appenders could be found for logger (org.elasticsearch.plugins).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Module execution: 1145ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - TypeListeners creation: 23ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Scopes creation: 3ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Converters creation: 0ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Binding creation: 17ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Private environment creation: 1ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Injector construction: 0ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Binding initialization: 95ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Binding indexing: 1ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Collecting injection requests: 0ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Binding validation: 71ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Static validation: 0ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Instance member validation: 1ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Provider verification: 5ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Static member injection: 0ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Instance injection: 6ms
[DEBUG] org.elasticsearch.common.inject.internal.Stopwatch - Preloading singletons: 129ms
[DEBUG] eu.cloudopting.logging.LoggingAspect - Enter: eu.cloudopting.repository.CustomAuditEventRepository.auditEventRepository() with argument[s] = []
[DEBUG] eu.cloudopting.logging.LoggingAspect - Exit: eu.cloudopting.repository.CustomAuditEventRepository.auditEventRepository() with result = eu.cloudopting.repository.CustomAuditEventRepository$1@4a467f08
[DEBUG] eu.cloudopting.config.apidoc.SwaggerConfiguration - Starting Swagger
[DEBUG] eu.cloudopting.config.apidoc.SwaggerConfiguration - Started Swagger in 30 ms
[INFO] eu.cloudopting.Application - Started Application in 139.214 seconds (JVM running for 142.623)

Please provide more information (code/configuration changes and not committed)

**Comment by xeviscc** [comment]
Seems to work now. May be it was a network problem with the server.
