### ISSUE TITLE
StoreService removal method.

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#41]
A method to remove content previously inserted into the JackRabbit Store should be exposed in the StoreService interface.

**Comment by ciprianpavel** [comment]
please check remove method from StoreService

**Comment by gioppoluca** [comment]
Please this is to all ... all need to See and test code where method are used or it will be Very Long to close. Parte of the team Cannot work isolated producing code without knowing where is used. This help understand what the team need and limit recycle.

**Comment by ciprianpavel** [comment]
I have added the method "remove" to the "StoreService" interface.
I have committed the code.
I have assigned the issue to the owner of the issue in order to know that the issue was worked on and check that the results are fine and the fix is correct.
What is wrong with this approach?

**Comment by guidospadotto-profesia** [comment]
I have implemented my own method to perform that (while waiting). 
It is StoreService.deletePath
@ciprianpavel If you implement a method, please document its input/output parameters with JavaDoc, so components depending on it know what to pass/what they get.

**Comment by ciprianpavel** [comment]
added method comments in 59d005e
