### ISSUE TITLE
Add Cloud Account SAVE button doesn't seem to work

### ISSUE THREAD

**Issue by gcabezas** [CloudOpting/cloudopting-manager#412]
In Account menu, Cloud Accounts, when trying to add a new cloud account, the SAVE button doesn't seem to work.

**Comment by xeviscc** [comment]
I cannot reproduce the issue. I tested with an admin user and a subscriber user.
Admin:
![image](https://cloud.githubusercontent.com/assets/10829055/19181304/76c8b7fa-8c6c-11e6-806d-e2964ee10fa4.png)
Subscriber:
![image](https://cloud.githubusercontent.com/assets/10829055/19181316/8baf3ed2-8c6c-11e6-9c83-9fcd129d1395.png)

Publisher and Operator are not able to add Cloud Accounts
