### ISSUE TITLE
Optional query parameters /api/application

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#42]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint to get all applications |
| **Screen that needs the endpoint:** |  Service Catalog |
| **Endpoint required:** |  /api/application |
| **Call Type:** | GET |
| **Response Data Type:** | application/json |
| **Query Parameters:** | page(Integer), size(Integer), sortBy("field name"), sortOrder(["asc", "desc"]), filter(String) |

We should have some parameters as optional, and have a default.
At least:
* **sortBy** (we should have a creation date for applications, and set the default order by the creation date, at the moment we can set the order by application name)
* **sortOrder** (we should order it by default to 'asc')
* **filter** (by default should be empty string, meaning ALL)

**Comment by xeviscc** [comment]
@cpopsa Could you please write down the status of this endpoint?

**Comment by ciprianpavel** [comment]
done.
