### ISSUE TITLE
Publishing process is not finalized

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#421]
Just tried the publishing process on DEV environment http://dev.cloudopting.org/ and the process does not show any error but the service is left with status = DRAFT. There is no function to move it from status=DRAFT to status=PUBLISHED. 
An instance for the service may be created but the service itself does not appear in the public catalog.

Please check the publish workflow.,

**Comment by PeterN-github** [comment]
This is same issue as "#419 Non valid status after publication".

**Comment by ciprianpavel** [comment]
yes, it is right!
