### ISSUE TITLE
User activation page layout

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#423]
User activation page layout is not inline with the layout of site as in the next picture
![image](https://cloud.githubusercontent.com/assets/10402949/19765992/08e9f99a-9c54-11e6-950d-d7e0a07904b8.png)

**Comment by xeviscc** [comment]
Changed in orther to be inline.
![image](https://cloud.githubusercontent.com/assets/10829055/22921431/f9648a98-f299-11e6-8fed-dc9cb1b91fd2.png)
