### ISSUE TITLE
reCAPTCHA error

### ISSUE THREAD

**Issue by gcabezas** [CloudOpting/cloudopting-manager#427]
CAPTCHA error when trying to register new user in dev environment.

Image added.

![captcha](https://cloud.githubusercontent.com/assets/11294634/20264382/83e0f99e-aa6b-11e6-864a-acd30f110562.jpg)

**Comment by xeviscc** [comment]
I've tested it in lab1.cloudopting.org and in http://dev.cloudopting.org/ and it worked for me. Did you deploy it in another URL?

**Comment by gcabezas** [comment]
I opened it in 151.80.170.176 and didn't work.

http://dev.cloudopting.org/ worked fine!

2016-11-14 15:46 GMT+01:00 Xavier Cases Camats <notifications@github.com>:

**Comment by gcabezas** [comment]
Sorry, I tryed it in http://151.80.170.176/ and didn't work. 

Address http://dev.cloudopting.org/ works fine!
