### ISSUE TITLE
[database] application_media columns

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#43]
It is really necessary save media with bytea format inside the database?
Could we save a URL pointing to the Jackrabbit repository instead?

So then we will change:
* **media_content** column from bytea to character varying(256)

**Comment by xeviscc** [comment]
@gioppoluca @guidospadotto-profesia @cpopsa 
We need an update on this, what do you think about?

**Comment by guidospadotto-profesia** [comment]
Application Resources are saved in JackRabbit. No need for those columns. I would remove them.

**Comment by xeviscc** [comment]
Remember to remove it from both databases.

**Comment by guidospadotto-profesia** [comment]
I have no idea whatsoever on how to do that correctly. @cpopsa ?

**Comment by ciprianpavel** [comment]
I have change PROD database according to requirement.
DEV database was changed by somebody else and there is no column in "application_media".

**Comment by guidospadotto-profesia** [comment]
Just for personal knowledge, what does it take to alter the OR Mapping entities?
1: Change the annotations in Java
2: Alter manually the tables in the Database
Is this all?
