### ISSUE TITLE
Enpoints to modify Organizations

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#45]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve all organizations. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/organization |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve an organization. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/organization/{idOrganization} |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to create an organization. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** |  /api/organization |
| **Call Type:** | POST |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to modify an organization. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** |  /api/organization |
| **Call Type:** | PUT |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to delete an organization. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/organization/{idOrganization} |
| **Call Type:** | DELETE |

**Comment by cpopsa** [comment]
Done
