### ISSUE TITLE
Modify constraints on ORGANIZATIONS table

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#49]
We have to modify some constrains on the ORGANIZATION table.

The constraint of NOT NULL of the organization_activation_date and organization_decomission_date should be deleted, in order to set it when it is required.

The status_id should point to the new table ORGANIZATION_STATUS

**NOTE**: It has to be created on both databases.

**Comment by cpopsa** [comment]
Done
