### ISSUE TITLE
DB migration

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#5]
Just to port here an issue from Daniel.
We need to version and keep under control also the DB.
I liked his option of using flyway if anyone has experience on the subject please contribute here

**Comment by ciprianpavel** [comment]
This may provide useful during initial development when the data model is not stable and everyone was using its own database. Right now, when the data model is stable and there is a central DB for development there is no use of such component.

**Comment by xeviscc** [comment]
This issue can be handled as an enhancement in the 'Backlog'

**Comment by guidospadotto-profesia** [comment]
Using flyway as of today.
