### ISSUE TITLE
Enpoints to modify Users

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#51]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve all users. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/users |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to create a user. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** |  /api/users |
| **Call Type:** | POST |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve a user. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/users/{idUser} |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to modify a user. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** |  /api/users/{idUser} |
| **Call Type:** | PUT |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to delete a user. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/users/{idUser} |
| **Call Type:** | DELETE |

**Comment by xeviscc** [comment]
@cpopsa, @pdaniel, @ciprianpavel 
Could you please estimate when this will be done?

**Comment by cpopsa** [comment]
It is done.
