### ISSUE TITLE
New endpoint /api/contact POST

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#53]
A new endpoint to save contact information is required.

A part from the endpoint a new table in database has to be created. CONTACT_FORM or CONTACT with the following columns Name, Email, Phone, Message, Company (Name).

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to post information about a contact. It will: <ul><li>1.Save the information provided into the database.</li><li>2. Send an email to cloudopting@gmail.com with the information.</li><li>3. Send an email to the user to confirm the reception of the email.</li></ul> |
| **Screen that needs the endpoint:** |  Contact Us Form |
| **Endpoint required:** |  /api/contact |
| **Call Type:** | POST |

You can see the form in the following image (the company is missing):
![screenshot-form-cloudopting](https://cloud.githubusercontent.com/assets/10829055/10820825/79da8a08-7e4f-11e5-8354-4a3c9d716a3a.png)

**Comment by cpopsa** [comment]
Please test the new endpoint after the problem in #79 is resolved.

**Comment by xeviscc** [comment]
Tested and working. Due to some network problems I will test again in order to see if mails are sent correctly.
