### ISSUE TITLE
Published service is not on the catalog

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#54]
When a service is published it cannot be seen in the catalog or in the service list.

**Comment by xeviscc** [comment]
After performing the following call:

**Request URL:** http://localhost:8080/api/application/unpaginated
**Request Method:** GET
**Status Code:** 200 OK

It returns soemthing like:

```json
content: [{id: 233, applicationMedias: null, organizationId: null,…},…]
first: true
last: false
number: 0
numberOfElements: 20
size: 20
sort: null
totalElements: 23
totalPages: 2
```

It seems that the "unpaginated" endpoint is paginated at the end.

**Comment by ciprianpavel** [comment]
is it linked with #56 ?

**Comment by xeviscc** [comment]
Fixed.
