### ISSUE TITLE
Field 'application_tosca_template' in 'applications' table remains empty

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#55]
The path of the TOSCA archive seems that is not saved into the database, so it cannot be recovered in the future.

**Comment by xeviscc** [comment]
The path to the jacrabbit should be saved in this column in order to ease things.

**Comment by guidospadotto-profesia** [comment]
It should be saved from commit e52831bdc2cb2016028b590f3c591f8a52cb36c2.
@gioppoluca the content of this field is the path to the file uploaded during publishing, and stored in JackRabbit. If this is not what you need, please comment.

**Comment by gioppoluca** [comment]
Yes is the path and name like in the examples in the DB rows (I placed them by hand)
