### ISSUE TITLE
"eu.cloudopting.exception.ToscaException: File not good" after trying to upload files on publication 

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#58]
I always get this error if I try to upload files in the publication wizard.

Has it some restrictions on the type of the file? Could you please spcify it?
@guidospadotto-profesia @gioppoluca

**Comment by guidospadotto-profesia** [comment]
A ToscaException is raised by the ToscaService.validateToscaCsar method if the input parameter is 
empty:

public boolean validateToscaCsar(String csarPath) throws ToscaException{
		boolean isValid = true;
		if(csarPath.isEmpty()){
			throw new ToscaException("File not good");
		}
		//Perform validation here and change the value of isValid accordingly
		return isValid;
	}

The file path is provided within the PublishToscaUploadTask.execute() method. You should put a breakpoint on line 36 and see if you get a value for the execution variable "filePath.

The handling of the Tosca Archive upload is triggered at line 272 of BpmnService.upload().

**Comment by xeviscc** [comment]
It seems that the line 228 of the BpmnService.java generates the excpetion.

```java
final File tempFile = File.createTempFile(uploadName+"|", "tmp");
````

**Comment by guidospadotto-profesia** [comment]
I have used "___" as separator, that should be compatible with Windows.
From commit e52831bdc2cb2016028b590f3c591f8a52cb36c2

**Comment by xeviscc** [comment]
It works!
