### ISSUE TITLE
Service list paginated to 20 but no pagination in the UI

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#59]
The new services are not shown in the UI because they are paginated to 20 records in the DB we had 24 and the query collect them in some random order.
UI must show paginated results allowing to see all pages of results

**Comment by xeviscc** [comment]
The same as https://github.com/CloudOpting/cloudopting-manager/issues/54
The UI is using an "unpaginated" endpoint, so it is expected a list of all the services.
