### ISSUE TITLE
Service records are not sorted by any means

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#60]
At the moment the query select services in no ordering.
Unless differently chosen by the UI the ordering MUST be alphabetic based on the service name

**Comment by gioppoluca** [comment]
Why assign to me? Please verify Fix and Close when done

**Comment by ciprianpavel** [comment]
I have verified the fix, otherwise I would not commit it. I have assigned it to in you in order to verify it by yourself and close it if you are satisfied with the outcome.
