### ISSUE TITLE
Service list does not have labels

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#61]
I have the latest pull and the service labels in the table are like "list.col.name" are we missing some labels?
We need to fix this.

**Comment by gioppoluca** [comment]
Strange after a refresh labels showed up ... strange.
Closing

**Comment by xeviscc** [comment]
It happens to me also, maybe it is related to the cache or the lag between showing the "key" and loading the file that contains the "value".
