### ISSUE TITLE
Endpoints to edit cloud accounts

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#65]
| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve all cloudaccounts from an organization. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** |  /api/organization/{idOrganization}/cloudaccounts |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to create a cloudaccount. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** |   /api/organization/{idOrganization}/cloudaccounts |
| **Call Type:** | POST |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to modify a cloudaccount. |
| **Screen that needs the endpoint:** |   Manage Organizations / Users |
| **Endpoint required:** | /api/organization/{idOrganization}/cloudaccounts |
| **Call Type:** | PUT |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to retrieve a cloudaccount. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** | /api/organization/{idOrganization}/cloudaccounts/{idCloudAccount} |
| **Call Type:** | GET |

| Description |  Values |
|---|---|
| **Description:** |  Endpoint used to delete a cloudaccount. |
| **Screen that needs the endpoint:** |  Manage Organizations / Users |
| **Endpoint required:** | /api/organization/{idOrganization}/cloudaccounts/{idCloudAccount} |
| **Call Type:** | DELETE |

**Comment by cpopsa** [comment]
Done
