### ISSUE TITLE
New endpoint "GET /api/roles "

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#67]
It will return all the roles in the application.

The JSON will look like:

```json
{
  "roles" : {
    "ROLE_SUBSCRIBER",
    "ROLE_ADMIN"
  }
}
```

**Comment by cpopsa** [comment]
The response will be like this:

[
  {
    "name": "ROLE_ADMIN"
  },
  {
    "name": "ROLE_USER"
  },
  {
    "name": "ROLE_SUBSCRIBER"
  },
  {
    "name": "ROLE_PUBLISHER"
  },
  {
    "name": "ROLE_OPERATOR"
  }
]
