### ISSUE TITLE
webui-component and docker-component

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#7]
We already have the cloudopting-manager-webui repository, do we still need the cloudopting-manager/webui-component/? What will be used it for?

I understand that in the case of cloudopting-manager-docker is diferent, because we have the main implementation in python outside the manager and the java interface inside the manager "cloudopting-manager/docker-component/"

**Comment by gioppoluca** [comment]
The webui-component has to go away.
You are correct I will delete asap.
