### ISSUE TITLE
Adding a boolean to the api/process

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#70]
The bpmn controller has been modified to accept a boolean value named "isTesting" we need to add it to the "press the button" page and now that api can be used in the instances list (after having choosen the cloud etc) to test the toscafile.

**Comment by xeviscc** [comment]
Button "Create Instance" redirects to the "Form Generation Screen" so it is needed after the Generation.

**Comment by xeviscc** [comment]
isTesting query parameter added when calling the api/process endpoint.
