### ISSUE TITLE
PUBLISH process: after initial data I'm requested to add at least something in the library - this is wrong

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#71]
After the metadata of the service I'm asked to add something to the library.
This is wrong that part has to be optional.
If I do not have any file to attach to the project I need to ba able to go to the tosca file immediately.
Check if a change in the process is needed or is just UI problem

**Comment by guidospadotto-profesia** [comment]
This is against what we originally designed, and it affects the process definition. However I will change it accordingly.

**Comment by gioppoluca** [comment]
Why we defined that way?
Am I forgetting something?

**Comment by guidospadotto-profesia** [comment]
If I remember correctly it was to force the end user to provide the logos, CSSs and other "static" resources. I don't know if this use case is still relevant.

**Comment by guidospadotto-profesia** [comment]
Fixed in commit a3e4f2b .
