### ISSUE TITLE
Service edit

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#73]
We need to be able to edit a service to change the tosca file

**Comment by xeviscc** [comment]
@guidospadotto-profesia Do we need to have other endpoints or modify the existing ones in order to be able to perform an update?

**Comment by guidospadotto-profesia** [comment]
I think we need a sort of "update" process that is exactly like the publishing process but does not create a new entry. 
This new process will get the Service Id as input and will retrieve/update the associated entity.

**Comment by xeviscc** [comment]
Same as https://github.com/CloudOpting/cloudopting-manager/issues/202 ?
We have to close one.

**Comment by xeviscc** [comment]
For more information see https://github.com/CloudOpting/cloudopting-manager/issues/202

**Comment by xeviscc** [comment]
Depends on #222 and #221

**Comment by xeviscc** [comment]
Due to dependencies, it will be posponed till the next release

**Comment by gioppoluca** [comment]
At @xeviscc @guidospadotto-profesia we need to close this.
Please concentrate on the editing of the publish and the publish in general.
We need to be sure that all errors get trapped and things do not get stuck

**Comment by xeviscc** [comment]
It still depends on #222 and #221. I will test #222 in the next days.
