### ISSUE TITLE
Customization table wrong defaults

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#74]
In  the customization table we need to have the decommission date to be nullable otherwise we are adding customizations that are always decommisisoned.
Also activation date need to be nullable

**Comment by gioppoluca** [comment]
Can you fix the mode in java?

**Comment by gioppoluca** [comment]
Db already changed in dev

**Comment by guidospadotto-profesia** [comment]
Done in ab35f91
