### ISSUE TITLE
Handle Ajax failures by providing feedback within the UI

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#76]
All Ajax callbacks should manage an error return in some User-friendly way (at least a notification in the UI).

In case of session timeouts/invalid credentials, the UI should redirect to the Login page.

[DEBUG] eu.cloudopting.security.Http401UnauthorizedEntryPoint - Pre-authenticated entry point called. Rejecting access

**Comment by xeviscc** [comment]
Now all services allow to control ajax failures with a callback function.
