### ISSUE TITLE
Platform independence

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#78]
The software should be able to run on all platforms and have no dependency on OS or J2EE environment.

**Comment by xeviscc** [comment]
Are we talking about the cloudopting-manager?

**Comment by ignasijr** [comment]
Agree with ciprian, the hackathon users might have MAC OSX to test it and WON'T Work, work around?

**Comment by xeviscc** [comment]
As stated yesterday in the meeting, in the hackathon a stable production environment should be used in order to developers struggle with TOSCA files, puppet, docker and thats it. They do not have to play installing the cloudopting-manager.

**Comment by xeviscc** [comment]
The platform does not need to be platform independent it has been dockerized. It can be found here: https://github.com/CloudOpting/deploy-cloudopting

For the hackathon a new common environment will be provided.
