### ISSUE TITLE
Docker-compose return info

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#8]
We need to define the return value for the runDockerCompose API.
What can docker-compose return to enable us to come back asynch to check the status?

**Comment by j-fuentes** [comment]
All the asynchronous operations with this API will return a token. This token can be used to check the status of the operation and also to cancel the operation.

**Comment by j-fuentes** [comment]
I have change the docker-component interface in order to abstract the REST API. Now, for the java application there is no token but a simple `isFinished()` method. Errors will raise a DockerError exception with the detail inside.

**Comment by gioppoluca** [comment]
Implemented in crane and new workflow
