### ISSUE TITLE
Failure on Form Generation Screen

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#85]
The Form Generation Screen caches the last parameters asked to the user.

As can be seen in the screenshot, only one parameter is asked, four appear in the form:

![image](https://cloud.githubusercontent.com/assets/10829055/11717420/a8e8d170-9f50-11e5-91b6-f3b31b13e4d8.png)

**Comment by gioppoluca** [comment]
Do not understand can you write down steps to reproduce?

**Comment by xeviscc** [comment]
Ok, I will try to explain step by step.

**Setp 1:** I create a service of Mongo with this: https://github.com/CloudOpting/pilots/tree/master/EXP-03-CityAngenda_Next2Me/_generated/csi-MongoC4C

**Step 2:** I customize this service and a new instance is created.

**Step 3:** I create a service of Apache(Http) with this: https://github.com/CloudOpting/pilots/tree/master/EXP-03-CityAngenda_Next2Me/_generated/csi-HttpC4C

**Step 4:** When I go to "Create an Instance" the Form Generation screen shows me the params from Mongo and the params from Http. 
In the screenshot can be seen that only one parameter is required from HttpC4C server ("servername"). Check editor in the left.
If you look at the Form Generation screen, the orchestrator asks me for the "servername" and also for information about a database that HttpC4C does not have.

**Conclusion:** I get to the conclusion that it was because some sort of cache in the orchestrator from the previous "Created instance", the MongoC4C.

**Comment by xeviscc** [comment]
@gioppoluca Is this issue related to cache problems? It depens on the issue https://github.com/CloudOpting/cloudopting-manager/issues/103 ?

**Comment by xeviscc** [comment]
Closed due its inactivity.
