### ISSUE TITLE
Add form to choose the cloud account after pressing deploy in customization list

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#87]
In the customization list when you press the deploy button the system needs to ask you to choose between the different cloud account you can use (the ones from your organization).
Than qith this information it will be possible to invoke a proper page where the result of the deploy are shown.

in total we need 2 pages more (the forst for choosing the cloud_account, the final for the deploy results)

**Comment by gioppoluca** [comment]
After some reasoning we should place the choice of the cloud account after the service customization.
Please define after the page of the customization form something that after a proper return code (you need to tell me what to return you) you change the page to the one where you present the choice of the cloud account to use for that customization:
it has to be the customizations visible to the organization of the current user.

**Comment by xeviscc** [comment]
@gioppoluca Do you mean that?

![cloudopting deploy testing flow](https://cloud.githubusercontent.com/assets/10829055/11814582/e157697c-a347-11e5-8b40-79d6365ae173.png)

**Comment by gioppoluca** [comment]
No.
1st path:
service list -> customization -> choose cloud account -> customization end

2nd path
subscription  -> customization -> choose cloud account -> customization end

**Comment by gioppoluca** [comment]
I considered that is wiser to have the cloud choice during the customization process since is stuff done by the subscriber.
Or the provider can do it from the list, but always in the customization phase.
We do not need BPM since are 2 steps

**Comment by xeviscc** [comment]
Ok, I think it is a third path:

When you want to "Test" a Service.

Here represented in a diagram:

![cloudopting deploy testing flow](https://cloud.githubusercontent.com/assets/10829055/11815854/02fd2232-a34e-11e5-946a-ae10b510dfc9.png)

**Comment by gioppoluca** [comment]
Not quite:
Subscribe path correct!
Test path:
will operate on a customization and the customization is generated from this chain: "service list"->"create instance"->"choose clud account"
OR from this chain:
"subscribe"->"create instance"->"choose clud account"

**Comment by gioppoluca** [comment]
Deploy and test start from the customization so once we set it during either the "service list"->"create instance" OR the "subscribe"->"create instance" we are good to go

**Comment by xeviscc** [comment]
OK, I think now I have it:

![cloudopting deploy testing flow](https://cloud.githubusercontent.com/assets/10829055/11840841/434251a4-a3f9-11e5-9d51-c1696efefeaa.png)

**Comment by xeviscc** [comment]
@guidospadotto-profesia What do you think about integrating this process in BPMN?

**Comment by xeviscc** [comment]
Depending on issue https://github.com/CloudOpting/cloudopting-manager/issues/96 in order to test it properly.

**Comment by xeviscc** [comment]
The issue #96 did not solved the problem. A new one was raised in order to fix this out. 
New dependency on https://github.com/CloudOpting/cloudopting-manager/issues/105

**Comment by gioppoluca** [comment]
Any news on this?

**Comment by xeviscc** [comment]
Done.
