### ISSUE TITLE
Manage cloud account

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#89]
We need the cloud account management pages.
As a subscriber or as a service provider (and also as admin) I need to be able to manage the cloud accounts of my organization.
Add, delete, edit, list them
I should be able to have a page where I can list the cloud accounts (maybe in the home page of the user?).

**Comment by xeviscc** [comment]
This issue depends on https://github.com/CloudOpting/cloudopting-manager/issues/96

**Comment by xeviscc** [comment]
Cloud Account managing is working.
Only missing the selector for cloud account providers.

**Comment by gioppoluca** [comment]
Can we try to close this asap?
