### ISSUE TITLE
Define the physical format of a Tosca Archive

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#9]
In order to upload and eventually validate a "Tosca Archive" within the "Service Publishing" process, the packaging format (zip file?) and contents of it have to be defined.
Once they are defined, the Validation activity within the Publishing process will be able to distinguish all required artifacts within the archive itself and perform the specific validations for each of them.

**Comment by xeviscc** [comment]
A definition of the CSAR file can be found in the following link: http://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.html#_Toc356403711

**Comment by gioppoluca** [comment]
Yes the format is known and defined in the standard we will stick to that.
The Tosca component will mange its complexity
