### ISSUE TITLE
Wrong start page in users info

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#98]
In the home page at start before login we have :
Name: {{name}}

![screenshot-cloudopting - mozilla firefox](https://cloud.githubusercontent.com/assets/1488715/11815181/e34ac82a-a34a-11e5-85c9-69985d807840.png)

**Comment by xeviscc** [comment]
@gioppoluca The issue should be fixed. Could you test it again and close the issue?
